import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedisclucheniyawidget/generated/GeneratedButtonsWidget516.dart';
import 'package:flutterapp/sabsusapp/generatedisclucheniyawidget/generated/GeneratedAppbarWidget58.dart';
import 'package:flutterapp/sabsusapp/generatedisclucheniyawidget/generated/GeneratedButtonsWidget518.dart';
import 'package:flutterapp/sabsusapp/generatedisclucheniyawidget/generated/GeneratedFrame3377Widget.dart';
import 'package:flutterapp/sabsusapp/generatedisclucheniyawidget/generated/GeneratedFrame3374Widget.dart';
import 'package:flutterapp/sabsusapp/generatedisclucheniyawidget/generated/GeneratedFrame3375Widget.dart';
import 'package:flutterapp/sabsusapp/generatedisclucheniyawidget/generated/GeneratedFrame3376Widget.dart';

/* Frame Isclucheniya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIsclucheniyaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedAppbarWidget58(),
        ),
        Positioned(
          left: 22.0,
          top: 107.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 45.0,
          child: GeneratedFrame3374Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 172.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 44.0,
          child: GeneratedFrame3377Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 236.0,
          right: null,
          bottom: null,
          width: 90.0,
          height: 30.0,
          child: GeneratedButtonsWidget516(),
        ),
        Positioned(
          left: 22.0,
          top: 286.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 45.0,
          child: GeneratedFrame3375Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 351.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 44.0,
          child: GeneratedFrame3376Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 415.0,
          right: null,
          bottom: null,
          width: 90.0,
          height: 30.0,
          child: GeneratedButtonsWidget518(),
        )
      ]),
    ));
  }
}
