import 'package:flutter/material.dart';

/* UndefinedNode Frame 3458
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3458Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
