import 'package:flutter/material.dart';

/* UndefinedNode Outline
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOutlineWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
