import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedGroup3294Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget246.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget254.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTagsWidget5.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedADDnoWidget56.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedWidget795.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget251.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget245.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget253.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget244.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget248.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget250.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget247.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget249.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedInputTextWidget252.dart';
import 'package:flutterapp/sabsusapp/generatedaddsotrudnicovwidget/generated/GeneratedGroup3249Widget1.dart';

/* Frame add sotrudnicov
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddsotrudnicovWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1392.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1392.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 40.0,
                            right: null,
                            bottom: null,
                            width: 348.0,
                            height: 22.0,
                            child: GeneratedWidget795(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.39487179487179486;

                              final double height =
                                  constraints.maxHeight * 0.10632183908045977;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.30256410256410254,
                                    y: constraints.maxHeight *
                                        0.05747126436781609,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedGroup3249Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 248.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget244(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 331.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget245(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 414.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget246(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 497.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget247(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 580.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget248(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 663.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget249(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 746.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget250(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 829.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 65.0,
                            child: GeneratedInputTextWidget251(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 914.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 57.0,
                            child: GeneratedGroup3294Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 991.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget252(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1074.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget253(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1157.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget254(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1240.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 67.0,
                            child: GeneratedInputTagsWidget5(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1327.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 40.0,
                            child: GeneratedADDnoWidget56(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
