import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedkategoriitranzakziiwidget/generated/GeneratedNamekolichesdvoaddWidget21.dart';
import 'package:flutterapp/sabsusapp/generatedkategoriitranzakziiwidget/generated/GeneratedAppbarWidget38.dart';
import 'package:flutterapp/sabsusapp/generatedkategoriitranzakziiwidget/generated/GeneratedPoickWidget21.dart';
import 'package:flutterapp/sabsusapp/generatedkategoriitranzakziiwidget/generated/GeneratedFrame3473Widget62.dart';

/* Frame kategorii tranzakzii
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKategoriitranzakziiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 389.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 345.0,
            height: 62.0,
            child: GeneratedAppbarWidget38(),
          ),
          Positioned(
            left: 22.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 345.0,
            height: 40.0,
            child: GeneratedNamekolichesdvoaddWidget21(),
          ),
          Positioned(
            left: 22.0,
            top: 167.0,
            right: null,
            bottom: null,
            width: 345.0,
            height: 38.0,
            child: GeneratedPoickWidget21(),
          ),
          Positioned(
            left: 22.0,
            top: 225.0,
            right: null,
            bottom: null,
            width: 345.0,
            height: 594.0,
            child: GeneratedFrame3473Widget62(),
          )
        ]),
      ),
    ));
  }
}
