import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedporolnewwidget/generated/GeneratedWidget264.dart';
import 'package:flutterapp/sabsusapp/generatedporolnewwidget/generated/Generated4Widget5.dart';
import 'package:flutterapp/sabsusapp/generatedporolnewwidget/generated/GeneratedWidget265.dart';
import 'package:flutterapp/sabsusapp/generatedporolnewwidget/generated/GeneratedGroup1698Widget2.dart';
import 'package:flutterapp/sabsusapp/generatedporolnewwidget/generated/GeneratedGroup1698Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedporolnewwidget/generated/GeneratedButtonsWidget121.dart';

/* Frame porolnew
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPorolnewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 88.0,
            child: GeneratedWidget264(),
          ),
          Positioned(
            left: 22.0,
            top: 146.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 56.0,
            child: GeneratedWidget265(),
          ),
          Positioned(
            left: 22.0,
            top: 220.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 56.0,
            child: GeneratedGroup1698Widget1(),
          ),
          Positioned(
            left: 22.0,
            top: 296.0,
            right: null,
            bottom: null,
            width: 314.0,
            height: 50.0,
            child: Generated4Widget5(),
          ),
          Positioned(
            left: 22.0,
            top: 364.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 56.0,
            child: GeneratedGroup1698Widget2(),
          ),
          Positioned(
            left: 22.0,
            top: 440.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 52.0,
            child: GeneratedButtonsWidget121(),
          )
        ]),
      ),
    ));
  }
}
