import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedpovarstartsmenawidget/generated/GeneratedFluorWidget19.dart';
import 'package:flutterapp/sabsusapp/generatedpovarstartsmenawidget/generated/GeneratedFrame3469Widget30.dart';

/* Frame povar start smena
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPovarstartsmenaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 30.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 694.0,
          child: GeneratedFrame3469Widget30(),
        ),
        Positioned(
          left: 0.0,
          top: 744.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 100.0,
          child: GeneratedFluorWidget19(),
        )
      ]),
    ));
  }
}
