import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedlistmessengewidget/generated/GeneratedAppbarWidget69.dart';
import 'package:flutterapp/sabsusapp/generatedlistmessengewidget/generated/GeneratedFrame3458Widget52.dart';
import 'package:flutterapp/sabsusapp/generatedlistmessengewidget/generated/GeneratedFrame3458Widget53.dart';

/* Frame list messenge
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListmessengeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 62.0,
          child: GeneratedAppbarWidget69(),
        ),
        Positioned(
          left: 0.0,
          top: 107.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 93.0,
          child: GeneratedFrame3458Widget52(),
        ),
        Positioned(
          left: 0.0,
          top: 220.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 150.0,
          child: GeneratedFrame3458Widget53(),
        )
      ]),
    ));
  }
}
