import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatednumenclaturaprodovecwidget/generated/GeneratedFrame3326Widget1.dart';
import 'package:flutterapp/sabsusapp/generatednumenclaturaprodovecwidget/generated/GeneratedFrame3473Widget338.dart';
import 'package:flutterapp/sabsusapp/generatednumenclaturaprodovecwidget/generated/GeneratedFluorWidget17.dart';

/* Frame numenclaturaprodovec
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNumenclaturaprodovecWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 20.0,
            child: GeneratedFrame3326Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 80.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 619.0,
            child: GeneratedFrame3473Widget338(),
          ),
          Positioned(
            left: 0.0,
            top: 719.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 100.0,
            child: GeneratedFluorWidget17(),
          )
        ]),
      ),
    ));
  }
}
