import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredinventarizaciyawidget/generated/GeneratedFrame3473Widget32.dart';
import 'package:flutterapp/sabsusapp/generatedredinventarizaciyawidget/generated/GeneratedADDnoWidget11.dart';
import 'package:flutterapp/sabsusapp/generatedredinventarizaciyawidget/generated/GeneratedWidget388.dart';

/* Frame red inventarizaciya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedinventarizaciyaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 40.0,
          right: null,
          bottom: null,
          width: 348.0,
          height: 22.0,
          child: GeneratedWidget388(),
        ),
        Positioned(
          left: 22.0,
          top: 80.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 679.0,
          child: GeneratedFrame3473Widget32(),
        ),
        Positioned(
          left: 22.0,
          top: 779.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedADDnoWidget11(),
        )
      ]),
    ));
  }
}
