import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedprofilmprogvecwidget/generated/GeneratedFluorWidget15.dart';
import 'package:flutterapp/sabsusapp/generatedprofilmprogvecwidget/generated/GeneratedFrame3445Widget3.dart';

/* Frame profilmprogvec
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilmprogvecWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 40.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 684.0,
          child: GeneratedFrame3445Widget3(),
        ),
        Positioned(
          left: 0.0,
          top: 744.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 100.0,
          child: GeneratedFluorWidget15(),
        )
      ]),
    ));
  }
}
