import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generateddiscuntwidget/generated/GeneratedFrame3458Widget29.dart';
import 'package:flutterapp/sabsusapp/generateddiscuntwidget/generated/GeneratedFrame701Widget.dart';
import 'package:flutterapp/sabsusapp/generateddiscuntwidget/generated/GeneratedFluorWidget2.dart';

/* Frame discunt
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscuntWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 249, 247, 252),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 25.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 93.0,
              child: GeneratedFrame3458Widget29(),
            ),
            Positioned(
              left: 0.0,
              top: 127.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 608.0,
              child: GeneratedFrame701Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 744.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 100.0,
              child: GeneratedFluorWidget2(),
            )
          ]),
    ));
  }
}
