import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedcalendar12widget/generated/GeneratedElementsDaypickerWidget3.dart';
import 'package:flutterapp/sabsusapp/generatedcalendar12widget/generated/GeneratedElementsDaypickerWidget4.dart';
import 'package:flutterapp/sabsusapp/generatedcalendar12widget/generated/GeneratedElementsDaypickerWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedcalendar12widget/generated/GeneratedElementsDaypickerWidget6.dart';
import 'package:flutterapp/sabsusapp/generatedcalendar12widget/generated/GeneratedElementsDaypickerWidget7.dart';
import 'package:flutterapp/sabsusapp/generatedcalendar12widget/generated/GeneratedElementsDaypickerWidget.dart';
import 'package:flutterapp/sabsusapp/generatedcalendar12widget/generated/GeneratedElementsDaypickerWidget2.dart';
import 'package:flutterapp/sabsusapp/generatedcalendar12widget/generated/GeneratedElementsDaypickerWidget5.dart';

/* Component Calendar-12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendar12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(24.0),
      child: Container(
        width: 339.0,
        height: 65.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(24.0),
                child: Container(
                  color: Color.fromARGB(255, 249, 247, 252),
                ),
              ),
              Positioned(
                left: -37.5,
                top: 6.5,
                right: null,
                bottom: null,
                width: 50.0,
                height: 52.0,
                child: GeneratedElementsDaypickerWidget(),
              ),
              Positioned(
                left: 14.5,
                top: 6.5,
                right: null,
                bottom: null,
                width: 50.0,
                height: 52.0,
                child: GeneratedElementsDaypickerWidget1(),
              ),
              Positioned(
                left: 66.5,
                top: 6.5,
                right: null,
                bottom: null,
                width: 50.0,
                height: 52.0,
                child: GeneratedElementsDaypickerWidget2(),
              ),
              Positioned(
                left: 118.5,
                top: 6.5,
                right: null,
                bottom: null,
                width: 50.0,
                height: 52.0,
                child: GeneratedElementsDaypickerWidget3(),
              ),
              Positioned(
                left: 170.5,
                top: 6.5,
                right: null,
                bottom: null,
                width: 50.0,
                height: 52.0,
                child: GeneratedElementsDaypickerWidget4(),
              ),
              Positioned(
                left: 222.5,
                top: 6.5,
                right: null,
                bottom: null,
                width: 50.0,
                height: 52.0,
                child: GeneratedElementsDaypickerWidget5(),
              ),
              Positioned(
                left: 274.5,
                top: 6.5,
                right: null,
                bottom: null,
                width: 50.0,
                height: 52.0,
                child: GeneratedElementsDaypickerWidget6(),
              ),
              Positioned(
                left: 326.5,
                top: 6.5,
                right: null,
                bottom: null,
                width: 50.0,
                height: 52.0,
                child: GeneratedElementsDaypickerWidget7(),
              )
            ]),
      ),
    ));
  }
}
