import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedvsestatusiwidget/generated/GeneratedAppbarWidget82.dart';
import 'package:flutterapp/sabsusapp/generatedvsestatusiwidget/generated/GeneratedMenuWidget8.dart';
import 'package:flutterapp/sabsusapp/generatedvsestatusiwidget/generated/GeneratedOdersWidget.dart';

/* Frame vse statusi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVsestatusiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 40.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 50.0,
          child: GeneratedAppbarWidget82(),
        ),
        Positioned(
          left: 22.0,
          top: 110.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 30.0,
          child: GeneratedMenuWidget8(),
        ),
        Positioned(
          left: 22.0,
          top: 160.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 664.0,
          child: GeneratedOdersWidget(),
        )
      ]),
    ));
  }
}
