import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedGroup3356Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget403.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedWidget966.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedADDnoWidget67.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget401.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedWidget965.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget398.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget406.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedFrame3249Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget402.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedMenuVerticalWidget149.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedButtonsWidget524.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget399.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget404.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget405.dart';
import 'package:flutterapp/sabsusapp/generatedredclientwidget/generated/GeneratedInputTextWidget400.dart';

/* Frame redclient
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedclientWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1666.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1666.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 40.0,
                            right: null,
                            bottom: null,
                            width: 348.0,
                            height: 22.0,
                            child: GeneratedWidget965(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 80.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 148.0,
                            child: GeneratedFrame3249Widget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 248.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget398(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 331.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget399(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 414.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 65.0,
                            child: GeneratedInputTextWidget400(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 499.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 36.0,
                            child: GeneratedMenuVerticalWidget149(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 555.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 65.0,
                            child: GeneratedInputTextWidget401(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 640.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget402(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 723.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget403(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 806.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget404(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 889.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget405(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 972.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget406(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1055.0,
                            right: null,
                            bottom: null,
                            width: 351.0,
                            height: 21.0,
                            child: GeneratedWidget966(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1091.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 430.0,
                            child: GeneratedGroup3356Widget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1541.0,
                            right: null,
                            bottom: null,
                            width: 232.51199340820312,
                            height: 40.0,
                            child: GeneratedButtonsWidget524(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1601.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 40.0,
                            child: GeneratedADDnoWidget67(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
