import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedmorediscuntwidget/generated/GeneratedFrame3457Widget19.dart';
import 'package:flutterapp/sabsusapp/generatedmorediscuntwidget/generated/GeneratedWidget117.dart';
import 'package:flutterapp/sabsusapp/generatedmorediscuntwidget/generated/Generated100030Widget.dart';
import 'package:flutterapp/sabsusapp/generatedmorediscuntwidget/generated/GeneratedFrame3457Widget16.dart';
import 'package:flutterapp/sabsusapp/generatedmorediscuntwidget/generated/GeneratedFrame3457Widget18.dart';
import 'package:flutterapp/sabsusapp/generatedmorediscuntwidget/generated/GeneratedFrame3457Widget17.dart';
import 'package:flutterapp/sabsusapp/generatedmorediscuntwidget/generated/GeneratedFrame720Widget7.dart';
import 'package:flutterapp/sabsusapp/generatedmorediscuntwidget/generated/GeneratedFrame3457Widget15.dart';

/* Frame more discunt
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMorediscuntWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedFrame720Widget7(),
        ),
        Positioned(
          left: 22.0,
          top: 105.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 168.0,
          child: GeneratedFrame3457Widget15(),
        ),
        Positioned(
          left: 22.0,
          top: 291.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedFrame3457Widget16(),
        ),
        Positioned(
          left: 22.0,
          top: 349.0,
          right: null,
          bottom: null,
          width: 348.0,
          height: 42.0,
          child: Generated100030Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 407.0,
          right: null,
          bottom: null,
          width: 348.0,
          height: 22.0,
          child: GeneratedWidget117(),
        ),
        Positioned(
          left: 22.0,
          top: 445.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedFrame3457Widget17(),
        ),
        Positioned(
          left: 22.0,
          top: 503.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedFrame3457Widget18(),
        ),
        Positioned(
          left: 22.0,
          top: 561.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 179.0,
          child: GeneratedFrame3457Widget19(),
        )
      ]),
    ));
  }
}
