import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedfluorwidget/generated/GeneratedButtemflurWidget2.dart';
import 'package:flutterapp/sabsusapp/generatedfluorwidget/generated/GeneratedButtemflurWidget.dart';
import 'package:flutterapp/sabsusapp/generatedfluorwidget/generated/GeneratedButtemflurWidget3.dart';
import 'package:flutterapp/sabsusapp/generatedfluorwidget/generated/GeneratedButtemflurWidget1.dart';

/* Component fluor
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFluorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 322.0,
      height: 100.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 20.0,
          top: 26.0,
          right: null,
          bottom: null,
          width: 60.0,
          height: 48.0,
          child: GeneratedButtemflurWidget(),
        ),
        Positioned(
          left: 94.0,
          top: 26.0,
          right: null,
          bottom: null,
          width: 60.0,
          height: 48.0,
          child: GeneratedButtemflurWidget1(),
        ),
        Positioned(
          left: 168.0,
          top: 26.0,
          right: null,
          bottom: null,
          width: 60.0,
          height: 48.0,
          child: GeneratedButtemflurWidget2(),
        ),
        Positioned(
          left: 242.0,
          top: 26.0,
          right: null,
          bottom: null,
          width: 60.0,
          height: 48.0,
          child: GeneratedButtemflurWidget3(),
        )
      ]),
    ));
  }
}
