import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedFrame3473Widget154.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedADDnoWidget49.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedInputTextWidget229.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedFrame3473Widget155.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedWidget781.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedWidget784.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedFrame3327Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedFrame3336Widget7.dart';
import 'package:flutterapp/sabsusapp/generatedredtaibelwidget/generated/GeneratedRectangle1874Widget1.dart';

/* Frame red taibel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedtaibelWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 858.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 22.0,
            child: GeneratedWidget781(),
          ),
          Positioned(
            left: 22.0,
            top: 80.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 223.0,
            child: GeneratedFrame3327Widget1(),
          ),
          Positioned(
            left: 22.0,
            top: 323.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 63.0,
            child: GeneratedFrame3336Widget7(),
          ),
          Positioned(
            left: 22.0,
            top: 406.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 63.0,
            child: GeneratedInputTextWidget229(),
          ),
          Positioned(
            left: 22.0,
            top: 489.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 18.0,
            child: GeneratedWidget784(),
          ),
          Positioned(
            left: 22.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 80.0,
            child: GeneratedFrame3473Widget154(),
          ),
          Positioned(
            left: 22.0,
            top: 625.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 80.0,
            child: GeneratedFrame3473Widget155(),
          ),
          Positioned(
            left: 22.0,
            top: 725.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 48.0,
            child: GeneratedRectangle1874Widget1(),
          ),
          Positioned(
            left: 22.0,
            top: 793.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedADDnoWidget49(),
          )
        ]),
      ),
    ));
  }
}
