description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-100.ttf"
          style: "normal"
          weight: 100
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Inter-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Anton"
      fonts: 
        - 
          asset: "fonts/Anton-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "DM Sans"
      fonts: 
        - 
          asset: "fonts/DMSans-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/DMSans-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/DMSans-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Poppins-300.ttf"
          style: "normal"
          weight: 300
        - 
          asset: "fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Nunito"
      fonts: 
        - 
          asset: "fonts/Nunito-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Nunito-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Lato"
      fonts: 
        - 
          asset: "fonts/Lato-regular.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Archivo"
      fonts: 
        - 
          asset: "fonts/Archivo-600.ttf"
          style: "normal"
          weight: 600
    - 
      family: "Open Sans"
      fonts: 
        - 
          asset: "fonts/OpenSans-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/OpenSans-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
