import 'package:flutter/material.dart';

/* UndefinedNode Menu Vertical
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuVerticalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
