import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedoplatapodpiskiwidget/generated/GeneratedAddnewcardWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedoplatapodpiskiwidget/generated/GeneratedAppbarWidget46.dart';

/* Frame OPLATA PODPISKI
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOPLATAPODPISKIWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 62.0,
            child: GeneratedAppbarWidget46(),
          ),
          Positioned(
            left: 0.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 370.0,
            child: GeneratedAddnewcardWidget1(),
          )
        ]),
      ),
    ));
  }
}
