import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedperedzakritiemzakroichekiwidget/generated/GeneratedFrame3473Widget196.dart';

/* Frame pered zakritiem zakroi cheki
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPeredzakritiemzakroichekiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 794.0,
            child: GeneratedFrame3473Widget196(),
          )
        ]),
      ),
    ));
  }
}
