import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedgrupclietswidget/generated/GeneratedNamekolichesdvoaddWidget12.dart';
import 'package:flutterapp/sabsusapp/generatedgrupclietswidget/generated/GeneratedPoickWidget12.dart';
import 'package:flutterapp/sabsusapp/generatedgrupclietswidget/generated/GeneratedFrame3473Widget49.dart';
import 'package:flutterapp/sabsusapp/generatedgrupclietswidget/generated/GeneratedAppbarWidget29.dart';

/* Frame grup cliets
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGrupclietsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 62.0,
            child: GeneratedAppbarWidget29(),
          ),
          Positioned(
            left: 22.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedNamekolichesdvoaddWidget12(),
          ),
          Positioned(
            left: 22.0,
            top: 167.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 38.0,
            child: GeneratedPoickWidget12(),
          ),
          Positioned(
            left: 22.0,
            top: 225.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 84.0,
            child: GeneratedFrame3473Widget49(),
          )
        ]),
      ),
    ));
  }
}
