import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedtipseellwidget/generated/GeneratedFrame3445Widget5.dart';

/* Frame tip seell
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTipseellWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 248.0,
      height: 196.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 22.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 204.0,
          height: 196.0,
          child: GeneratedFrame3445Widget5(),
        )
      ]),
    ));
  }
}
