import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedregistracommpaniiwidget/generated/GeneratedGroup1700Widget.dart';
import 'package:flutterapp/sabsusapp/generatedregistracommpaniiwidget/generated/GeneratedGroup1699Widget.dart';
import 'package:flutterapp/sabsusapp/generatedregistracommpaniiwidget/generated/GeneratedGroup1696Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedregistracommpaniiwidget/generated/GeneratedButtonsWidget133.dart';
import 'package:flutterapp/sabsusapp/generatedregistracommpaniiwidget/generated/GeneratedGroup1697Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedregistracommpaniiwidget/generated/GeneratedGroup1698Widget3.dart';
import 'package:flutterapp/sabsusapp/generatedregistracommpaniiwidget/generated/GeneratedFrame720Widget8.dart';

/* Frame registra commpanii
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistracommpaniiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.8871794871794871;

              final double height = constraints.maxHeight * 0.07345971563981042;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.05641025641025641,
                    y: constraints.maxHeight * 0.02962085308056872,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedFrame720Widget8(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 22.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 58.0,
            child: GeneratedGroup1697Widget2(),
          ),
          Positioned(
            left: 22.0,
            top: 185.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 58.0,
            child: GeneratedGroup1696Widget1(),
          ),
          Positioned(
            left: 22.0,
            top: 263.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 58.0,
            child: GeneratedGroup1698Widget3(),
          ),
          Positioned(
            left: 22.0,
            top: 341.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 58.0,
            child: GeneratedGroup1699Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 419.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 58.0,
            child: GeneratedGroup1700Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 497.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 52.0,
            child: GeneratedButtonsWidget133(),
          )
        ]),
      ),
    ));
  }
}
