import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedcodbezopwidget/generated/Generated4Widget7.dart';
import 'package:flutterapp/sabsusapp/generatedcodbezopwidget/generated/GeneratedFrame3409Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedcodbezopwidget/generated/GeneratedFrame3410Widget.dart';
import 'package:flutterapp/sabsusapp/generatedcodbezopwidget/generated/Generatedxxxxxx6789Widget.dart';
import 'package:flutterapp/sabsusapp/generatedcodbezopwidget/generated/GeneratedButtonsWidget124.dart';
import 'package:flutterapp/sabsusapp/generatedcodbezopwidget/generated/GeneratedAppbarWidget16.dart';
import 'package:flutterapp/sabsusapp/generatedcodbezopwidget/generated/GeneratedWidget275.dart';
import 'package:flutterapp/sabsusapp/generatedcodbezopwidget/generated/GeneratedWidget274.dart';

/* Frame cod bezop
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCodbezopWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedAppbarWidget16(),
        ),
        Positioned(
          left: 22.0,
          top: 107.0,
          right: null,
          bottom: null,
          width: 348.0,
          height: 88.0,
          child: Generated4Widget7(),
        ),
        Positioned(
          left: 22.0,
          top: 213.0,
          right: null,
          bottom: null,
          width: 348.0,
          height: 83.0,
          child: Generatedxxxxxx6789Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 314.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 70.0,
          child: GeneratedFrame3409Widget1(),
        ),
        Positioned(
          left: 22.0,
          top: 404.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 21.0,
          child: GeneratedFrame3410Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 445.0,
          right: null,
          bottom: null,
          width: 348.0,
          height: 23.0,
          child: GeneratedWidget274(),
        ),
        Positioned(
          left: 22.0,
          top: 486.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 43.0,
          child: GeneratedWidget275(),
        ),
        Positioned(
          left: 22.0,
          top: 549.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 52.0,
          child: GeneratedButtonsWidget124(),
        )
      ]),
    ));
  }
}
