import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedvchodwidget/generated/GeneratedAppbarWidget17.dart';
import 'package:flutterapp/sabsusapp/generatedvchodwidget/generated/GeneratedFrame3457Widget61.dart';
import 'package:flutterapp/sabsusapp/generatedvchodwidget/generated/GeneratedButtonsWidget130.dart';

/* Frame vchod
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVchodWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedAppbarWidget17(),
        ),
        Positioned(
          left: 22.0,
          top: 117.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 632.0,
          child: GeneratedFrame3457Widget61(),
        ),
        Positioned(
          left: 22.0,
          top: 779.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedButtonsWidget130(),
        )
      ]),
    ));
  }
}
