import 'package:flutter/material.dart';

/* UndefinedNode restuarant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRestuarantWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
