import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredskladwidget/generated/GeneratedADDnoWidget47.dart';
import 'package:flutterapp/sabsusapp/generatedredskladwidget/generated/GeneratedFrame3473Widget151.dart';

/* Frame red sklad
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedskladWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 281.0,
            child: GeneratedFrame3473Widget151(),
          ),
          Positioned(
            left: 22.0,
            top: 341.0,
            right: null,
            bottom: null,
            width: 345.0,
            height: 40.0,
            child: GeneratedADDnoWidget47(),
          )
        ]),
      ),
    ));
  }
}
