import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedozenitkurrierwidget/generated/GeneratedGroup3466Widget.dart';
import 'package:flutterapp/sabsusapp/generatedozenitkurrierwidget/generated/GeneratedAppbarWidget2.dart';
import 'package:flutterapp/sabsusapp/generatedozenitkurrierwidget/generated/GeneratedFrame3467Widget1.dart';

/* Frame ozenit kurrier
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOzenitkurrierWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 77.0,
          child: GeneratedAppbarWidget2(),
        ),
        Positioned(
          left: 0.0,
          top: 97.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 650.0,
          child: GeneratedFrame3467Widget1(),
        ),
        Positioned(
          left: 22.0,
          top: 767.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 52.0,
          child: GeneratedGroup3466Widget(),
        )
      ]),
    ));
  }
}
