import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedostatkiwidget/generated/GeneratedPoickWidget2.dart';
import 'package:flutterapp/sabsusapp/generatedostatkiwidget/generated/GeneratedAppbarWidget19.dart';
import 'package:flutterapp/sabsusapp/generatedostatkiwidget/generated/GeneratedFrame3473Widget18.dart';
import 'package:flutterapp/sabsusapp/generatedostatkiwidget/generated/GeneratedNamekolichesdvoaddWidget2.dart';

/* Frame ostatki
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOstatkiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 62.0,
            child: GeneratedAppbarWidget19(),
          ),
          Positioned(
            left: 25.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 340.0,
            height: 20.0,
            child: GeneratedNamekolichesdvoaddWidget2(),
          ),
          Positioned(
            left: 22.0,
            top: 147.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 38.0,
            child: GeneratedPoickWidget2(),
          ),
          Positioned(
            left: 22.0,
            top: 205.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 68.50436401367188,
            child: GeneratedFrame3473Widget18(),
          )
        ]),
      ),
    ));
  }
}
