import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedzacvedeniyawidget/generated/GeneratedFrame720Widget5.dart';
import 'package:flutterapp/sabsusapp/generatedzacvedeniyawidget/generated/GeneratedFrame3459Widget14.dart';

/* Frame zacvedeniya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedZacvedeniyaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 62.0,
          child: GeneratedFrame720Widget5(),
        ),
        Positioned(
          left: 0.0,
          top: 107.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 138.0,
          child: GeneratedFrame3459Widget14(),
        )
      ]),
    ));
  }
}
