import 'package:flutter/material.dart';

/* UndefinedNode buttem flur
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtemflurWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
