import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedframe3458widget/generated/GeneratedFrame3457Widget.dart';
import 'package:flutterapp/sabsusapp/generatedframe3458widget/generated/GeneratedGroup3456Widget.dart';

/* Component Frame 3458
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3458Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 93.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 0.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 283.0,
          height: 93.0,
          child: GeneratedFrame3457Widget(),
        ),
        Positioned(
          left: 328.0,
          top: 20.5,
          right: null,
          bottom: null,
          width: 52.0,
          height: 52.0,
          child: GeneratedGroup3456Widget(),
        )
      ]),
    ));
  }
}
