import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedframe3490widget/generated/GeneratedGroup3285Widget.dart';

/* Frame Frame 3490
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3490Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 336.00341796875,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: null,
          top: null,
          right: null,
          bottom: null,
          width: 390.0,
          height: 334.0,
          child: TransformHelper.translate(
              x: 1.09, y: -1.00, z: 0, child: GeneratedGroup3285Widget()),
        )
      ]),
    ));
  }
}
