import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedustroisvawidget/generated/GeneratedFrame3473Widget198.dart';
import 'package:flutterapp/sabsusapp/generatedustroisvawidget/generated/GeneratedAppbarWidget67.dart';

/* Frame ustroisva
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUstroisvaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 27.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 336.0,
            height: 62.0,
            child: GeneratedAppbarWidget67(),
          ),
          Positioned(
            left: 27.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 336.0,
            height: 712.0,
            child: GeneratedFrame3473Widget198(),
          )
        ]),
      ),
    ));
  }
}
