import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedmenusellwidget/generated/GeneratedFluorWidget9.dart';
import 'package:flutterapp/sabsusapp/generatedmenusellwidget/generated/GeneratedFrame3473Widget179.dart';

/* Frame menu sell
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenusellWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 983.7012939453125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 983.7012939453125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 25.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 843.7012939453125,
                            child: GeneratedFrame3473Widget179(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 883.7012939453125,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 100.0,
                            child: GeneratedFluorWidget9(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
