import 'package:flutter/material.dart';

/* UndefinedNode choeseproduct
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChoeseproductWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
