import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedadresslistwidget/generated/GeneratedDeliveryDetailsWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedadresslistwidget/generated/GeneratedFrame715Widget.dart';

/* Frame adress list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdresslistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 60.0,
          child: GeneratedFrame715Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 105.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 72.47601318359375,
          child: GeneratedDeliveryDetailsWidget1(),
        )
      ]),
    ));
  }
}
