import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredspisaniewidget/generated/GeneratedADDnoWidget13.dart';
import 'package:flutterapp/sabsusapp/generatedredspisaniewidget/generated/GeneratedWidget395.dart';
import 'package:flutterapp/sabsusapp/generatedredspisaniewidget/generated/GeneratedFrame3473Widget38.dart';

/* Frame red spisanie
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedspisanieWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 22.0,
            child: GeneratedWidget395(),
          ),
          Positioned(
            left: 22.0,
            top: 80.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 679.0,
            child: GeneratedFrame3473Widget38(),
          ),
          Positioned(
            left: 22.0,
            top: 779.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedADDnoWidget13(),
          )
        ]),
      ),
    ));
  }
}
