import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedvsesmenywidget/generated/GeneratedFrame3380Widget.dart';
import 'package:flutterapp/sabsusapp/generatedvsesmenywidget/generated/GeneratedAppbarWidget61.dart';
import 'package:flutterapp/sabsusapp/generatedvsesmenywidget/generated/GeneratedButtonsWidget541.dart';
import 'package:flutterapp/sabsusapp/generatedvsesmenywidget/generated/GeneratedFrame3423Widget.dart';

/* Frame vse smeny
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVsesmenyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedAppbarWidget61(),
        ),
        Positioned(
          left: 22.0,
          top: 107.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedFrame3380Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 189.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 558.0,
          child: GeneratedFrame3423Widget(),
        ),
        Positioned(
          left: 80.0,
          top: 767.0,
          right: null,
          bottom: null,
          width: 230.0,
          height: 52.0,
          child: GeneratedButtonsWidget541(),
        )
      ]),
    ));
  }
}
