import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedframe722widget1/generated/GeneratedGroup3198Widget1.dart';

/* Component Frame 722
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame722Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 53.0,
      height: 49.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 217, 217, 217),
          ),
        ),
        Positioned(
          left: 10.0,
          top: 10.0,
          right: null,
          bottom: null,
          width: 33.0,
          height: 29.0,
          child: GeneratedGroup3198Widget1(),
        )
      ]),
    ));
  }
}
