import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedarhivcgecovwidget/generated/GeneratedFluorWidget11.dart';
import 'package:flutterapp/sabsusapp/generatedarhivcgecovwidget/generated/GeneratedFrame3473Widget214.dart';
import 'package:flutterapp/sabsusapp/generatedarhivcgecovwidget/generated/GeneratedFrame3458Widget51.dart';

/* Frame arhiv cgecov
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArhivcgecovWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 93.0,
          child: GeneratedFrame3458Widget51(),
        ),
        Positioned(
          left: 0.0,
          top: 138.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 586.0,
          child: GeneratedFrame3473Widget214(),
        ),
        Positioned(
          left: 0.0,
          top: 744.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 100.0,
          child: GeneratedFluorWidget11(),
        )
      ]),
    ));
  }
}
