import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedbronirovaniyawidget/generated/GeneratedFrame3473Widget188.dart';
import 'package:flutterapp/sabsusapp/generatedbronirovaniyawidget/generated/GeneratedFrame3421Widget.dart';
import 'package:flutterapp/sabsusapp/generatedbronirovaniyawidget/generated/GeneratedAppbarWidget62.dart';

/* Frame bronirovaniya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBronirovaniyaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 249, 247, 252),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 72.0,
              child: GeneratedAppbarWidget62(),
            ),
            Positioned(
              left: 0.0,
              top: 92.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 40.0,
              child: GeneratedFrame3421Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 152.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 80.0,
              child: GeneratedFrame3473Widget188(),
            )
          ]),
    ));
  }
}
