import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedopensmenacassawidget/generated/GeneratedGroup3275Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedopensmenacassawidget/generated/GeneratedLoginWidget4.dart';
import 'package:flutterapp/sabsusapp/generatedopensmenacassawidget/generated/GeneratedInputTextWidget412.dart';
import 'package:flutterapp/sabsusapp/generatedopensmenacassawidget/generated/GeneratedInputTextWidget413.dart';
import 'package:flutterapp/sabsusapp/generatedopensmenacassawidget/generated/GeneratedWidget969.dart';
import 'package:flutterapp/sabsusapp/generatedopensmenacassawidget/generated/GeneratedButtonsWidget529.dart';

/* Frame opensmenacassa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOpensmenacassaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 46.0,
            child: GeneratedWidget969(),
          ),
          Positioned(
            left: 22.0,
            top: 104.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 63.0,
            child: GeneratedInputTextWidget412(),
          ),
          Positioned(
            left: 22.0,
            top: 187.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 90.0,
            child: GeneratedInputTextWidget413(),
          ),
          Positioned(
            left: 116.0,
            top: 297.0,
            right: null,
            bottom: null,
            width: 158.0,
            height: 52.0,
            child: GeneratedButtonsWidget529(),
          ),
          Positioned(
            left: 70.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 250.0,
            height: 325.0,
            child: GeneratedGroup3275Widget1(),
          ),
          Positioned(
            left: 167.5,
            top: 714.0,
            right: null,
            bottom: null,
            width: 60.0,
            height: 26.0,
            child: GeneratedLoginWidget4(),
          )
        ]),
      ),
    ));
  }
}
