import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedcodddwidget/generated/GeneratedButtonsWidget122.dart';
import 'package:flutterapp/sabsusapp/generatedcodddwidget/generated/GeneratedFrame3473Widget16.dart';
import 'package:flutterapp/sabsusapp/generatedcodddwidget/generated/GeneratedWidget270.dart';
import 'package:flutterapp/sabsusapp/generatedcodddwidget/generated/Generatedxxxxxx6789xxxxgmailcomWidget.dart';
import 'package:flutterapp/sabsusapp/generatedcodddwidget/generated/GeneratedWidget269.dart';
import 'package:flutterapp/sabsusapp/generatedcodddwidget/generated/Generated4Widget6.dart';
import 'package:flutterapp/sabsusapp/generatedcodddwidget/generated/GeneratedFrame3409Widget.dart';

/* Frame coddd
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCodddWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 88.0,
            child: Generated4Widget6(),
          ),
          Positioned(
            left: 22.0,
            top: 146.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 110.0,
            child: Generatedxxxxxx6789xxxxgmailcomWidget(),
          ),
          Positioned(
            left: 22.0,
            top: 274.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 70.0,
            child: GeneratedFrame3409Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 364.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 21.0,
            child: GeneratedFrame3473Widget16(),
          ),
          Positioned(
            left: 22.0,
            top: 405.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 23.0,
            child: GeneratedWidget269(),
          ),
          Positioned(
            left: 22.0,
            top: 446.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 43.0,
            child: GeneratedWidget270(),
          ),
          Positioned(
            left: 22.0,
            top: 509.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 52.0,
            child: GeneratedButtonsWidget122(),
          )
        ]),
      ),
    ));
  }
}
