import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedpopolnitdeposschetwidget/generated/GeneratedADDnoWidget73.dart';
import 'package:flutterapp/sabsusapp/generatedpopolnitdeposschetwidget/generated/GeneratedAppbarWidget66.dart';
import 'package:flutterapp/sabsusapp/generatedpopolnitdeposschetwidget/generated/GeneratedFrame3445Widget1.dart';

/* Frame Popolnit depos schet
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPopolnitdeposschetWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedAppbarWidget66(),
        ),
        Positioned(
          left: 22.0,
          top: 115.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 636.0,
          child: GeneratedFrame3445Widget1(),
        ),
        Positioned(
          left: 22.0,
          top: 779.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedADDnoWidget73(),
        )
      ]),
    ));
  }
}
