import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedpincodwidget/generated/GeneratedRectangle1849Widget.dart';
import 'package:flutterapp/sabsusapp/generatedpincodwidget/generated/GeneratedGroup3275Widget.dart';
import 'package:flutterapp/sabsusapp/generatedpincodwidget/generated/GeneratedGroup3471Widget.dart';
import 'package:flutterapp/sabsusapp/generatedpincodwidget/generated/GeneratedWidget968.dart';
import 'package:flutterapp/sabsusapp/generatedpincodwidget/generated/GeneratedLoginWidget3.dart';

/* Frame PINCOD
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPINCODWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 152.0,
            child: GeneratedRectangle1849Widget(),
          ),
          Positioned(
            left: 22.000045776367188,
            top: 212.0,
            right: null,
            bottom: null,
            width: 345.9999084472656,
            height: 70.0,
            child: GeneratedGroup3471Widget(),
          ),
          Positioned(
            left: 75.0,
            top: 302.0,
            right: null,
            bottom: null,
            width: 240.0,
            height: 325.0,
            child: GeneratedGroup3275Widget(),
          ),
          Positioned(
            left: 167.5,
            top: 647.0,
            right: null,
            bottom: null,
            width: 60.0,
            height: 26.0,
            child: GeneratedLoginWidget3(),
          ),
          Positioned(
            left: 22.0,
            top: 688.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 23.0,
            child: GeneratedWidget968(),
          )
        ]),
      ),
    ));
  }
}
