import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedmassegprodovecwidget/generated/GeneratedFrame3458Widget55.dart';
import 'package:flutterapp/sabsusapp/generatedmassegprodovecwidget/generated/GeneratedFluorWidget13.dart';
import 'package:flutterapp/sabsusapp/generatedmassegprodovecwidget/generated/GeneratedFrame701Widget9.dart';

/* Frame MASSEGprodovec
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMASSEGprodovecWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 849.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 93.0,
            child: GeneratedFrame3458Widget55(),
          ),
          Positioned(
            left: 0.0,
            top: 136.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 595.0,
            child: GeneratedFrame701Widget9(),
          ),
          Positioned(
            left: 0.0,
            top: 749.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 100.0,
            child: GeneratedFluorWidget13(),
          )
        ]),
      ),
    ));
  }
}
