import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget258.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget259.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget261.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget255.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget256.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget262.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedWidget797.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget257.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedADDnoWidget57.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedGroup3249Widget2.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedGroup3294Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget263.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget264.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget260.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTagsWidget6.dart';
import 'package:flutterapp/sabsusapp/generatedredsotrudnicovwidget/generated/GeneratedInputTextWidget265.dart';

/* Frame red sotrudnicov
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedsotrudnicovWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1392.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1392.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 40.0,
                            right: null,
                            bottom: null,
                            width: 348.0,
                            height: 22.0,
                            child: GeneratedWidget797(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.39487179487179486;

                              final double height =
                                  constraints.maxHeight * 0.10632183908045977;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.30256410256410254,
                                    y: constraints.maxHeight *
                                        0.05747126436781609,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedGroup3249Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 248.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget255(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 331.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget256(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 414.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget257(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 497.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget258(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 580.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget259(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 663.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget260(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 746.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget261(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 829.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 65.0,
                            child: GeneratedInputTextWidget262(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 914.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 57.0,
                            child: GeneratedGroup3294Widget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 991.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget263(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1074.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget264(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1157.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget265(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1240.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 67.0,
                            child: GeneratedInputTagsWidget6(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1327.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 40.0,
                            child: GeneratedADDnoWidget57(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
