import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedstatistikaprodashcwidget/generated/GeneratedFrame3473Widget225.dart';
import 'package:flutterapp/sabsusapp/generatedstatistikaprodashcwidget/generated/GeneratedAppbarWidget71.dart';
import 'package:flutterapp/sabsusapp/generatedstatistikaprodashcwidget/generated/GeneratedFrame3444Widget7.dart';

/* Frame Statistika prodashc
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStatistikaprodashcWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1128.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1128.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 25.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 62.0,
                            child: GeneratedAppbarWidget71(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 107.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 30.0,
                            child: GeneratedFrame3444Widget7(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 157.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 951.0,
                            child: GeneratedFrame3473Widget225(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
