import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedappbarwidget/generated/GeneratedButtonsWidget4.dart';
import 'package:flutterapp/sabsusapp/generatedappbarwidget/generated/GeneratedWidget.dart';

/* Component app bar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAppbarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 448.0,
      height: 62.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 20.0,
          top: 10.0,
          right: null,
          bottom: null,
          width: 52.0,
          height: 52.0,
          child: GeneratedButtonsWidget4(),
        ),
        Positioned(
          left: 77.0,
          top: 24.0,
          right: null,
          bottom: null,
          width: 296.0,
          height: 26.0,
          child: GeneratedWidget(),
        )
      ]),
    ));
  }
}
