import 'package:flutter/material.dart';

/* UndefinedNode categoru
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCategoruWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
