import 'package:flutter/material.dart';

/* UndefinedNode 3
    Autogenerated by FlutLab FTF Generator
  */
class Generated3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
