import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedbagwidget/generated/GeneratedFrame3457Widget22.dart';
import 'package:flutterapp/sabsusapp/generatedbagwidget/generated/GeneratedFrame3461Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedbagwidget/generated/GeneratedFrame3458Widget23.dart';

/* Frame bag
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBagWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 249, 247, 252),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 25.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 93.0,
              child: GeneratedFrame3458Widget23(),
            ),
            Positioned(
              left: 0.0,
              top: 123.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 425.3123779296875,
              child: GeneratedFrame3457Widget22(),
            ),
            Positioned(
              left: 0.0,
              top: 553.3123779296875,
              right: null,
              bottom: null,
              width: 390.0,
              height: 290.6876220703125,
              child: GeneratedFrame3461Widget1(),
            )
          ]),
    ));
  }
}
