import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedmetoduoplatuwidget/generated/GeneratedFrame3473Widget75.dart';
import 'package:flutterapp/sabsusapp/generatedmetoduoplatuwidget/generated/GeneratedNamekolichesdvoaddWidget27.dart';
import 'package:flutterapp/sabsusapp/generatedmetoduoplatuwidget/generated/GeneratedPoickWidget27.dart';
import 'package:flutterapp/sabsusapp/generatedmetoduoplatuwidget/generated/GeneratedAppbarWidget44.dart';

/* Frame Metodu oplatu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMetoduoplatuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 28.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 62.0,
            child: GeneratedAppbarWidget44(),
          ),
          Positioned(
            left: 22.0,
            top: 110.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedNamekolichesdvoaddWidget27(),
          ),
          Positioned(
            left: 22.0,
            top: 170.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 38.0,
            child: GeneratedPoickWidget27(),
          ),
          Positioned(
            left: 22.0,
            top: 228.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 98.0,
            child: GeneratedFrame3473Widget75(),
          )
        ]),
      ),
    ));
  }
}
