import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedselldeliverywidget/generated/GeneratedFrame3388Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedselldeliverywidget/generated/GeneratedFrame3337Widget2.dart';
import 'package:flutterapp/sabsusapp/generatedselldeliverywidget/generated/GeneratedFrame3458Widget50.dart';

/* Frame selldelivery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelldeliveryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 93.0,
          child: GeneratedFrame3458Widget50(),
        ),
        Positioned(
          left: 0.0,
          top: 138.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 352.0,
          child: GeneratedFrame3388Widget1(),
        ),
        Positioned(
          left: 0.0,
          top: 510.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 334.0,
          child: GeneratedFrame3337Widget2(),
        )
      ]),
    ));
  }
}
