import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedoderfinishdeliverywidget/generated/GeneratedFrame3458Widget32.dart';
import 'package:flutterapp/sabsusapp/generatedoderfinishdeliverywidget/generated/GeneratedFluorWidget5.dart';
import 'package:flutterapp/sabsusapp/generatedoderfinishdeliverywidget/generated/GeneratedFrame701Widget2.dart';

/* Frame oder finish delivery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOderfinishdeliveryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 93.0,
          child: GeneratedFrame3458Widget32(),
        ),
        Positioned(
          left: 0.0,
          top: 129.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 604.0,
          child: GeneratedFrame701Widget2(),
        ),
        Positioned(
          left: 0.0,
          top: 744.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 100.0,
          child: GeneratedFluorWidget5(),
        )
      ]),
    ));
  }
}
