import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedButtonsWidget46.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedRectangle1832Widget.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedWidget47.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedMenuVerticalWidget12.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedInputTextWidget7.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedInputTextWidget6.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedInputTextWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedInputTextWidget10.dart';
import 'package:flutterapp/sabsusapp/generatedadressaddwidget/generated/GeneratedInputTextWidget9.dart';

/* Frame adress add
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdressaddWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 249, 247, 252),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8923076923076924;

                final double height =
                    constraints.maxHeight * 0.026066350710900472;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: constraints.maxHeight * 0.04739336492890995,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget47(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                final double height =
                    constraints.maxHeight * 0.2890995260663507;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: constraints.maxHeight * 0.0947867298578199,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle1832Widget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                final double height =
                    constraints.maxHeight * 0.07701421800947868;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: constraints.maxHeight * 0.4075829383886256,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedInputTextWidget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                final double height =
                    constraints.maxHeight * 0.04976303317535545;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: constraints.maxHeight * 0.5082938388625592,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedInputTextWidget7(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                final double height =
                    constraints.maxHeight * 0.04976303317535545;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: constraints.maxHeight * 0.5817535545023697,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedInputTextWidget8(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                final double height =
                    constraints.maxHeight * 0.04976303317535545;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: constraints.maxHeight * 0.6552132701421801,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedInputTextWidget9(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                final double height =
                    constraints.maxHeight * 0.04976303317535545;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: constraints.maxHeight * 0.7286729857819905,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedInputTextWidget10(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: null,
              width: null,
              height: 36.0,
              child: TransformHelper.translate(
                  x: 0.00,
                  y: 273.00,
                  z: 0,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8871794871794871;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.05641025641025641,
                          y: 0,
                          z: 0,
                          child: Container(
                            width: width,
                            child: GeneratedMenuVerticalWidget12(),
                          ))
                    ]);
                  })),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                final double height =
                    constraints.maxHeight * 0.061611374407582936;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: constraints.maxHeight * 0.8684834123222749,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedButtonsWidget46(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
