import 'package:flutter/material.dart';

/* UndefinedNode Frame 3459
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3459Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
