import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedmessegedeliverywidget/generated/GeneratedFluorWidget6.dart';
import 'package:flutterapp/sabsusapp/generatedmessegedeliverywidget/generated/GeneratedFrame3458Widget33.dart';
import 'package:flutterapp/sabsusapp/generatedmessegedeliverywidget/generated/GeneratedFrame701Widget3.dart';

/* Frame messege delivery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessegedeliveryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 93.0,
          child: GeneratedFrame3458Widget33(),
        ),
        Positioned(
          left: 0.0,
          top: 131.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 600.0,
          child: GeneratedFrame701Widget3(),
        ),
        Positioned(
          left: 0.0,
          top: 744.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 100.0,
          child: GeneratedFluorWidget6(),
        )
      ]),
    ));
  }
}
