import 'package:flutter/material.dart';

/* UndefinedNode market
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMarketWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
