import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedframe3452widget/generated/GeneratedGroup3450Widget.dart';

/* Component Frame 3452
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3452Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 609.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 0.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 609.0,
          child: GeneratedGroup3450Widget(),
        )
      ]),
    ));
  }
}
