import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatednamekolichesdvoaddwidget/generated/GeneratedButtonsWidget8.dart';
import 'package:flutterapp/sabsusapp/generatednamekolichesdvoaddwidget/generated/GeneratedFrame3293Widget.dart';

/* Component name.kolichesdvo add
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNamekolichesdvoaddWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 40.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(127, 158, 158, 158),
            offset: Offset(5.0, 10.0),
            blurRadius: 25.0,
          ),
          BoxShadow(
            color: Color.fromARGB(255, 255, 255, 255),
            offset: Offset(-8.0, -8.0),
            blurRadius: 20.0,
          )
        ],
      ),
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 0.0,
          top: 10.0,
          right: null,
          bottom: null,
          width: 215.0,
          height: 20.0,
          child: GeneratedFrame3293Widget(),
        ),
        Positioned(
          left: null,
          top: 0.0,
          right: 0.0,
          bottom: null,
          width: 115.0,
          height: 40.0,
          child: GeneratedButtonsWidget8(),
        )
      ]),
    ));
  }
}
