import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedzalwidget/generated/GeneratedFrame722Widget.dart';
import 'package:flutterapp/sabsusapp/generatedzalwidget/generated/GeneratedGroup3199Widget.dart';
import 'package:flutterapp/sabsusapp/generatedzalwidget/generated/GeneratedRectangle1387Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component zal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedZalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 344.0,
      height: 215.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: 0,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedRectangle1387Widget(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.13953488372093023;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: 0,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedGroup3199Widget(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.15406976744186046;

            final double height = constraints.maxHeight * 0.22790697674418606;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05813953488372093,
                  y: constraints.maxHeight * 0.2837209302325581,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedFrame722Widget(),
                  ))
            ]);
          }),
        )
      ]),
    ));
  }
}
