import 'package:flutter/material.dart';

/* Rectangle Rectangle Inner Gray Shadow
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangleInnerGrayShadowWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 150.0,
      height: 50.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
        gradient: LinearGradient(
          begin: Alignment(0.0, -1.0),
          end: Alignment(0.0, 0.9999999999999998),
          stops: [0.0, 1.0],
          colors: [
            Color.fromARGB(255, 235, 237, 240),
            Color.fromARGB(255, 242, 244, 246)
          ],
        ),
      ),
    ));
  }
}
