import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generateduvedomleniewidget/generated/GeneratedFrame720Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generateduvedomleniewidget/generated/GeneratedFrame3457Widget9.dart';

/* Frame uvedomlenie
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUvedomlenieWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8871794871794871;

            final double height = constraints.maxHeight * 0.07345971563981042;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.02962085308056872,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedFrame720Widget2(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 22.0,
          top: 107.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 97.0,
          child: GeneratedFrame3457Widget9(),
        )
      ]),
    ));
  }
}
