import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedOclienteWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedOtveztiWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedUclientaWidget1.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedStatusodersWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedFrame3425Widget5.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedMapWidget3.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedSdachaWidget1.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedFrame3424Widget7.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedCamentWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedMasscallWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedNalichnieWidget1.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedFrame3431Widget25.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedFrame3424Widget8.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedAppbarWidget10.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderdrivewidget/generated/GeneratedKoplateWidget1.dart';

/* Frame Delivery oder drive
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeliveryoderdriveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1048.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1048.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 77.0,
                            child: GeneratedAppbarWidget10(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 97.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedStatusodersWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 142.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 50.0,
                            child: GeneratedFrame3424Widget7(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 212.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 176.0,
                            child: GeneratedMapWidget3(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 408.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 52.0,
                            child: GeneratedFrame3424Widget8(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 480.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedFrame3425Widget5(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 525.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 53.0,
                            child: GeneratedOclienteWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 598.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 40.0,
                            child: GeneratedMasscallWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 658.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedKoplateWidget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 703.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedNalichnieWidget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 748.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedUclientaWidget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 793.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedFrame3431Widget25(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 838.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedSdachaWidget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 883.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 80.0,
                            child: GeneratedCamentWidget(),
                          ),
                          Positioned(
                            left: 22.5,
                            top: 983.0,
                            right: null,
                            bottom: null,
                            width: 345.0,
                            height: 40.0,
                            child: GeneratedOtveztiWidget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
