import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedmenuuprwidget/generated/GeneratedFluorWidget16.dart';
import 'package:flutterapp/sabsusapp/generatedmenuuprwidget/generated/GeneratedFrame3469Widget27.dart';

/* Frame menu upr
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuuprWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 2685.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 2685.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 25.0,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 2540.0,
                            child: GeneratedFrame3469Widget27(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 2585.0,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 100.0,
                            child: GeneratedFluorWidget16(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
