import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedframe2widget5/generated/GeneratedFrame3457Widget93.dart';
import 'package:flutterapp/sabsusapp/generatedframe2widget5/generated/GeneratedFrame13Widget3.dart';
import 'package:flutterapp/sabsusapp/generatedframe2widget5/generated/GeneratedFrame15Widget3.dart';

/* Instance Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 300.0,
        height: 350.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
          border: Border.all(
            width: 3.0,
            color: Color.fromARGB(255, 211, 191, 249),
          ),
          gradient: RadialGradient(
            center: Alignment(-1.0000000000000002, -0.9999999999999996),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(102, 255, 255, 255),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 22.0,
            top: 22.0,
            right: null,
            bottom: null,
            width: 256.0,
            height: 214.0,
            child: GeneratedFrame13Widget3(),
          ),
          Positioned(
            left: 22.0,
            top: 246.0,
            right: null,
            bottom: null,
            width: 256.0,
            height: 31.0,
            child: GeneratedFrame15Widget3(),
          ),
          Positioned(
            left: 22.0,
            top: 287.0,
            right: null,
            bottom: null,
            width: 256.0,
            height: 40.0,
            child: GeneratedFrame3457Widget93(),
          )
        ]),
      ),
    ));
  }
}
