import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedstatusoderrwidget/generated/GeneratedFrame3465Widget.dart';

/* Frame status oderr
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStatusoderrWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 864.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 0.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 864.0,
          child: GeneratedFrame3465Widget(),
        )
      ]),
    ));
  }
}
