import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredcategoryindridietwidget/generated/GeneratedWidget769.dart';
import 'package:flutterapp/sabsusapp/generatedredcategoryindridietwidget/generated/GeneratedFrame3473Widget147.dart';
import 'package:flutterapp/sabsusapp/generatedredcategoryindridietwidget/generated/GeneratedADDnoWidget43.dart';

/* Frame red category indridiet
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedcategoryindridietWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 42.0,
            child: GeneratedWidget769(),
          ),
          Positioned(
            left: 22.0,
            top: 100.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 659.0,
            child: GeneratedFrame3473Widget147(),
          ),
          Positioned(
            left: 22.0,
            top: 779.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedADDnoWidget43(),
          )
        ]),
      ),
    ));
  }
}
