import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedpokypkiilwidget/generated/GeneratedFrame3458Widget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedpokypkiilwidget/generated/GeneratedAppbarWidget8.dart';

/* Frame pokypkiil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPokypkiilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: null,
          top: 0.0,
          right: null,
          bottom: 0.0,
          width: 346.0,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double height = constraints.maxHeight * 0.07464454976303317;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.02962085308056872,
                  z: 0,
                  child: Container(
                    height: height,
                    child: GeneratedAppbarWidget8(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 22.0,
          top: 108.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 610.0,
          child: GeneratedFrame3458Widget8(),
        )
      ]),
    ));
  }
}
