import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedprofiluprwidget/generated/GeneratedButtonsWidget630.dart';
import 'package:flutterapp/sabsusapp/generatedprofiluprwidget/generated/GeneratedGroup1696Widget2.dart';
import 'package:flutterapp/sabsusapp/generatedprofiluprwidget/generated/GeneratedGroup1699Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedprofiluprwidget/generated/GeneratedWidget1119.dart';
import 'package:flutterapp/sabsusapp/generatedprofiluprwidget/generated/GeneratedGroup3470Widget.dart';
import 'package:flutterapp/sabsusapp/generatedprofiluprwidget/generated/GeneratedGroup1698Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedprofiluprwidget/generated/GeneratedWidget1118.dart';

/* Frame profil upr
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfiluprWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.9;

              final double height = constraints.maxHeight * 0.04028436018957346;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.05641025641025641,
                    y: constraints.maxHeight * 0.04739336492890995,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedWidget1118(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.8923076923076924;

              final double height = constraints.maxHeight * 0.03672985781990521;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.05641025641025641,
                    y: constraints.maxHeight * 0.10545023696682465,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedWidget1119(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 117.5,
            top: 138.0,
            right: null,
            bottom: null,
            width: 155.0,
            height: 148.0,
            child: GeneratedGroup3470Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.8871794871794871;

              final double height = constraints.maxHeight * 0.07109004739336493;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.05641025641025641,
                    y: constraints.maxHeight * 0.36255924170616116,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedGroup1698Widget4(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.8871794871794871;

              final double height = constraints.maxHeight * 0.07109004739336493;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.05641025641025641,
                    y: constraints.maxHeight * 0.45734597156398105,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedGroup1699Widget1(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.8871794871794871;

              final double height = constraints.maxHeight * 0.07121255160507997;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.05641025641025641,
                    y: constraints.maxHeight * 0.5521327014218009,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedGroup1696Widget2(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.8871794871794871;

              final double height =
                  constraints.maxHeight * 0.061611374407582936;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.05641025641025641,
                    y: constraints.maxHeight * 0.6470419354913359,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedButtonsWidget630(),
                    ))
              ]);
            }),
          )
        ]),
      ),
    ));
  }
}
