import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedFrame3337Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedWidget646.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedFrame3336Widget2.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedInputTextWidget93.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedFrame3336Widget3.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedWidget647.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedADDnoWidget17.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedFrame3339Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedredingridientwidget/generated/GeneratedInputTextWidget96.dart';

/* Frame red ingridient
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedingridientWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1058.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1058.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 40.0,
                            right: null,
                            bottom: null,
                            width: 348.0,
                            height: 22.0,
                            child: GeneratedWidget646(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 80.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget93(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 163.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedFrame3336Widget2(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 246.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedFrame3339Widget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 329.0,
                            right: null,
                            bottom: null,
                            width: 351.0,
                            height: 21.0,
                            child: GeneratedWidget647(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 365.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 147.0,
                            child: GeneratedFrame3336Widget3(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 532.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 65.0,
                            child: GeneratedInputTextWidget96(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 617.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 356.0,
                            child: GeneratedFrame3337Widget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 993.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 40.0,
                            child: GeneratedADDnoWidget17(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
