import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedplusminuswidget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/sabsusapp/generatedplusminuswidget/generated/GeneratedPlusWidget.dart';
import 'package:flutterapp/sabsusapp/generatedplusminuswidget/generated/Generated1Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedplusminuswidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component plusminus
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlusminusWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 32.000003814697266,
      height: 82.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 2.562499694526232;

            final double height = constraints.maxHeight * 0.3902439024390244;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth,
                  y: constraints.maxHeight * 1.705810274604407e-8,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedRectangle33Widget(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.7499999105930435;

            final double height = constraints.maxHeight * 0.2926829268292683;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.8750000149011594,
                  y: constraints.maxHeight * 0.05204067579129847,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedGroup7Widget(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.5312499366700725;

            final double height = constraints.maxHeight * 0.35365853658536583;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.32812496088445653,
                  y: constraints.maxHeight * 0.36301626810213417,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: Generated1Widget1(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.7499999105930435;

            final double height = constraints.maxHeight * 0.2926829268292683;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.12500010430811592,
                  y: constraints.maxHeight * 0.6496016339557927,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedPlusWidget(),
                  ))
            ]);
          }),
        )
      ]),
    ));
  }
}
