import 'package:flutter/material.dart';

/* UndefinedNode Playment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlaymentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
