import 'package:flutter/material.dart';

/* UndefinedNode tip restuarant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTiprestuarantWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
