import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedizmenapodpiskiwidget/generated/GeneratedAppbarWidget45.dart';
import 'package:flutterapp/sabsusapp/generatedizmenapodpiskiwidget/generated/GeneratedButtonsWidget285.dart';
import 'package:flutterapp/sabsusapp/generatedizmenapodpiskiwidget/generated/GeneratedGroup3249Widget.dart';
import 'package:flutterapp/sabsusapp/generatedizmenapodpiskiwidget/generated/GeneratedGroup3250Widget.dart';

/* Frame izmena podpiski
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIzmenapodpiskiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 62.0,
            child: GeneratedAppbarWidget45(),
          ),
          Positioned(
            left: 22.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 60.0,
            child: GeneratedGroup3249Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 187.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedGroup3250Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 247.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 52.0,
            child: GeneratedButtonsWidget285(),
          )
        ]),
      ),
    ));
  }
}
