import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedComentWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedADDnoWidget1.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedFrame3424Widget12.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedFrame3433Widget2.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedFrame3425Widget7.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedMapWidget5.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedFrame3469Widget17.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedAppbarWidget12.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderonpleasewidget/generated/GeneratedFrame3424Widget11.dart';

/* Frame Delivery oder on please
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeliveryoderonpleaseWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 77.0,
          child: GeneratedAppbarWidget12(),
        ),
        Positioned(
          left: 22.0,
          top: 97.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 50.0,
          child: GeneratedFrame3424Widget11(),
        ),
        Positioned(
          left: 22.0,
          top: 167.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 176.0,
          child: GeneratedMapWidget5(),
        ),
        Positioned(
          left: 22.0,
          top: 363.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 52.0,
          child: GeneratedFrame3424Widget12(),
        ),
        Positioned(
          left: 22.0,
          top: 435.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 25.0,
          child: GeneratedFrame3425Widget7(),
        ),
        Positioned(
          left: 22.0,
          top: 480.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 53.0,
          child: GeneratedFrame3433Widget2(),
        ),
        Positioned(
          left: 22.0,
          top: 553.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedFrame3469Widget17(),
        ),
        Positioned(
          left: 22.0,
          top: 613.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 80.0,
          child: GeneratedComentWidget(),
        ),
        Positioned(
          left: 22.0,
          top: 713.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedADDnoWidget1(),
        )
      ]),
    ));
  }
}
