import 'package:flutter/material.dart';

/* UndefinedNode avatar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAvatarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
