import 'package:flutter/material.dart';

/* UndefinedNode discunt sell
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscuntsellWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
