import 'package:flutter/material.dart';

/* UndefinedNode oder delivery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOderdeliveryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
