import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedoplatawidget/generated/GeneratedFrame3462Widget11.dart';
import 'package:flutterapp/sabsusapp/generatedoplatawidget/generated/GeneratedFrame3462Widget9.dart';
import 'package:flutterapp/sabsusapp/generatedoplatawidget/generated/GeneratedContinueandPayWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedoplatawidget/generated/GeneratedAddnewWidget.dart';
import 'package:flutterapp/sabsusapp/generatedoplatawidget/generated/GeneratedFrame720Widget3.dart';
import 'package:flutterapp/sabsusapp/generatedoplatawidget/generated/GeneratedPaymentWidget.dart';
import 'package:flutterapp/sabsusapp/generatedoplatawidget/generated/GeneratedFrame3459Widget3.dart';
import 'package:flutterapp/sabsusapp/generatedoplatawidget/generated/GeneratedContinueandPayWidget1.dart';

/* Frame oplata
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOplataWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 896.73583984375,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 896.73583984375,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 249, 247, 252),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 25.0,
                              right: null,
                              bottom: null,
                              width: 390.0,
                              height: 62.0,
                              child: GeneratedFrame720Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 107.0,
                              right: null,
                              bottom: null,
                              width: 390.0,
                              height: 105.0,
                              child: GeneratedFrame3462Widget9(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 390.0,
                              height: 29.0,
                              child: GeneratedFrame3459Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: null,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 20.640230178833008,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -157.05,
                                  z: 0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: 0,
                                          y: 0,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            child: GeneratedAddnewWidget(),
                                          ))
                                    ]);
                                  })),
                            ),
                            Positioned(
                              left: -175.0,
                              top: 321.6402282714844,
                              right: null,
                              bottom: null,
                              width: 740.0,
                              height: 300.0,
                              child: GeneratedPaymentWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 641.6402587890625,
                              right: null,
                              bottom: null,
                              width: 390.0,
                              height: 77.19086456298828,
                              child: GeneratedFrame3462Widget11(),
                            ),
                            Positioned(
                              left: 67.5,
                              top: 738.8311157226562,
                              right: null,
                              bottom: null,
                              width: 255.0,
                              height: 53.0,
                              child: GeneratedContinueandPayWidget1(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 811.8311157226562,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 59.904762268066406,
                              child: GeneratedContinueandPayWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
