import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredprichinaspisaniewidget/generated/GeneratedWidget399.dart';
import 'package:flutterapp/sabsusapp/generatedredprichinaspisaniewidget/generated/GeneratedFrame3473Widget44.dart';
import 'package:flutterapp/sabsusapp/generatedredprichinaspisaniewidget/generated/GeneratedADDnoWidget15.dart';

/* Frame red prichina spisanie
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedprichinaspisanieWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 22.0,
            child: GeneratedWidget399(),
          ),
          Positioned(
            left: 22.0,
            top: 80.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 664.0,
            child: GeneratedFrame3473Widget44(),
          ),
          Positioned(
            left: 22.0,
            top: 764.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedADDnoWidget15(),
          )
        ]),
      ),
    ));
  }
}
