import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedmoreaboutproductwidget/generated/GeneratedFrame3473Widget15.dart';
import 'package:flutterapp/sabsusapp/generatedmoreaboutproductwidget/generated/GeneratedAppbarWidget15.dart';

/* Frame more about product 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMoreaboutproductWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 923.88427734375,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 923.88427734375,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 77.0,
                            child: GeneratedAppbarWidget15(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 77.0,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 846.88427734375,
                            child: GeneratedFrame3473Widget15(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
