import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedpodpiskawidget/generated/GeneratedFrame3473Widget78.dart';
import 'package:flutterapp/sabsusapp/generatedpodpiskawidget/generated/GeneratedWidget572.dart';
import 'package:flutterapp/sabsusapp/generatedpodpiskawidget/generated/GeneratedAppbarWidget47.dart';
import 'package:flutterapp/sabsusapp/generatedpodpiskawidget/generated/GeneratedFrame3256Widget.dart';
import 'package:flutterapp/sabsusapp/generatedpodpiskawidget/generated/GeneratedFrame3473Widget79.dart';
import 'package:flutterapp/sabsusapp/generatedpodpiskawidget/generated/GeneratedWidget576.dart';
import 'package:flutterapp/sabsusapp/generatedpodpiskawidget/generated/GeneratedButtonsWidget289.dart';

/* Frame podpiska
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPodpiskaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 62.0,
            child: GeneratedAppbarWidget47(),
          ),
          Positioned(
            left: 22.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 351.0,
            height: 25.0,
            child: GeneratedWidget572(),
          ),
          Positioned(
            left: 22.0,
            top: 147.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 20.0,
            child: GeneratedFrame3256Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 187.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 20.0,
            child: GeneratedFrame3473Widget78(),
          ),
          Positioned(
            left: 22.0,
            top: 227.0,
            right: null,
            bottom: null,
            width: 150.0,
            height: 30.0,
            child: GeneratedButtonsWidget289(),
          ),
          Positioned(
            left: 22.0,
            top: 277.0,
            right: null,
            bottom: null,
            width: 351.0,
            height: 25.0,
            child: GeneratedWidget576(),
          ),
          Positioned(
            left: 22.0,
            top: 317.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 77.0,
            child: GeneratedFrame3473Widget79(),
          )
        ]),
      ),
    ));
  }
}
