import 'package:flutter/material.dart';

/* UndefinedNode Buttons3D
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtons3DWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
