import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedRectangle1874Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedFrame3327Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedADDnoWidget48.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedFrame3336Widget6.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedWidget777.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedInputTextWidget227.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedFrame3473Widget152.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedFrame3473Widget153.dart';
import 'package:flutterapp/sabsusapp/generatedaddtaibelwidget/generated/GeneratedWidget780.dart';

/* Frame Add taibel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddtaibelWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 858.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 22.0,
            child: GeneratedWidget777(),
          ),
          Positioned(
            left: 22.0,
            top: 80.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 223.0,
            child: GeneratedFrame3327Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 323.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 63.0,
            child: GeneratedFrame3336Widget6(),
          ),
          Positioned(
            left: 22.0,
            top: 406.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 63.0,
            child: GeneratedInputTextWidget227(),
          ),
          Positioned(
            left: 22.0,
            top: 489.0,
            right: null,
            bottom: null,
            width: 348.0,
            height: 18.0,
            child: GeneratedWidget780(),
          ),
          Positioned(
            left: 22.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 80.0,
            child: GeneratedFrame3473Widget152(),
          ),
          Positioned(
            left: 22.0,
            top: 625.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 80.0,
            child: GeneratedFrame3473Widget153(),
          ),
          Positioned(
            left: 22.0,
            top: 725.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 48.0,
            child: GeneratedRectangle1874Widget(),
          ),
          Positioned(
            left: 22.0,
            top: 793.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedADDnoWidget48(),
          )
        ]),
      ),
    ));
  }
}
