import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedframe3492widget/generated/GeneratedMoreinformaishenWidget1.dart';

/* Frame Frame 3492
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3492Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 154.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 0.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 154.0,
          child: GeneratedMoreinformaishenWidget1(),
        )
      ]),
    ));
  }
}
