import 'package:flutter/material.dart';

/* UndefinedNode ADD no
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedADDnoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
