import 'package:flutter/material.dart';

/* UndefinedNode Dropdown
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDropdownWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
