import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedporolfinishwidget/generated/GeneratedWidget250.dart';
import 'package:flutterapp/sabsusapp/generatedporolfinishwidget/generated/GeneratedLoginWidget2.dart';
import 'package:flutterapp/sabsusapp/generatedporolfinishwidget/generated/GeneratedCheckmark1Widget.dart';
import 'package:flutterapp/sabsusapp/generatedporolfinishwidget/generated/GeneratedWidget249.dart';
import 'package:flutterapp/sabsusapp/generatedporolfinishwidget/generated/GeneratedButtonsWidget117.dart';

/* Frame porolfinish
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPorolfinishWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 140.5,
            top: 40.0,
            right: null,
            bottom: null,
            width: 109.0,
            height: 107.0,
            child: GeneratedCheckmark1Widget(),
          ),
          Positioned(
            left: 87.0,
            top: 167.0,
            right: null,
            bottom: null,
            width: 218.0,
            height: 131.0,
            child: GeneratedWidget249(),
          ),
          Positioned(
            left: 36.5,
            top: 316.0,
            right: null,
            bottom: null,
            width: 319.0,
            height: 56.0,
            child: GeneratedWidget250(),
          ),
          Positioned(
            left: 167.5,
            top: 390.0,
            right: null,
            bottom: null,
            width: 60.0,
            height: 26.0,
            child: GeneratedLoginWidget2(),
          ),
          Positioned(
            left: 136.0,
            top: 431.0,
            right: null,
            bottom: null,
            width: 118.0,
            height: 52.0,
            child: GeneratedButtonsWidget117(),
          )
        ]),
      ),
    ));
  }
}
