import 'package:flutter/material.dart';

/* UndefinedNode home food
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomefoodWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
