import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget8.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget10.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget6.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget5.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget3.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget2.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget7.dart';
import 'package:flutterapp/sabsusapp/generatedverticalmenuwidget/generated/GeneratedMenuVerticalWidget4.dart';

/* Component Vertical Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerticalMenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 260.0,
      height: 306.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * -0.0032679738562091504,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget2(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.10784313725490197,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget3(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.21895424836601307,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget4(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.8856209150326797,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget5(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.7745098039215687,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget6(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.3300653594771242,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget7(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.6633986928104575,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget8(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.4411764705882353,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget9(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth;

            final double height = constraints.maxHeight * 0.11764705882352941;

            return Stack(children: [
              TransformHelper.translate(
                  x: 0,
                  y: constraints.maxHeight * 0.5522875816993464,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedMenuVerticalWidget10(),
                  ))
            ]);
          }),
        )
      ]),
    ));
  }
}
