import 'package:flutter/material.dart';

/* UndefinedNode Group 3234
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup3234Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
