import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedzakritiesmenuwidget/generated/GeneratedInputTextWidget416.dart';
import 'package:flutterapp/sabsusapp/generatedzakritiesmenuwidget/generated/GeneratedButtonsWidget536.dart';
import 'package:flutterapp/sabsusapp/generatedzakritiesmenuwidget/generated/GeneratedInputTextWidget417.dart';
import 'package:flutterapp/sabsusapp/generatedzakritiesmenuwidget/generated/GeneratedAppbarWidget60.dart';
import 'package:flutterapp/sabsusapp/generatedzakritiesmenuwidget/generated/GeneratedWidget973.dart';
import 'package:flutterapp/sabsusapp/generatedzakritiesmenuwidget/generated/GeneratedInputTextWidget418.dart';

/* Frame zakritie smenu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedZakritiesmenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 0.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 77.0,
          child: GeneratedAppbarWidget60(),
        ),
        Positioned(
          left: 22.0,
          top: 97.0,
          right: null,
          bottom: null,
          width: 348.0,
          height: 26.0,
          child: GeneratedWidget973(),
        ),
        Positioned(
          left: 22.0,
          top: 141.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 69.0,
          child: GeneratedInputTextWidget416(),
        ),
        Positioned(
          left: 22.0,
          top: 230.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 69.0,
          child: GeneratedInputTextWidget417(),
        ),
        Positioned(
          left: 22.0,
          top: 319.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 69.0,
          child: GeneratedInputTextWidget418(),
        ),
        Positioned(
          left: 22.0,
          top: 408.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 52.0,
          child: GeneratedButtonsWidget536(),
        )
      ]),
    ));
  }
}
