import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedprigotovlenoewidget1/generated/GeneratedAppbarWidget86.dart';
import 'package:flutterapp/sabsusapp/generatedprigotovlenoewidget1/generated/GeneratedMenuWidget10.dart';
import 'package:flutterapp/sabsusapp/generatedprigotovlenoewidget1/generated/GeneratedOdersWidget2.dart';

/* Frame prigotovlenoe
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPrigotovlenoeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 40.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 50.0,
          child: GeneratedAppbarWidget86(),
        ),
        Positioned(
          left: 22.0,
          top: 110.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 30.0,
          child: GeneratedMenuWidget10(),
        ),
        Positioned(
          left: 22.0,
          top: 160.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 305.0,
          child: GeneratedOdersWidget2(),
        )
      ]),
    ));
  }
}
