import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedfototporolwidget/generated/GeneratedComponent18Widget.dart';
import 'package:flutterapp/sabsusapp/generatedfototporolwidget/generated/GeneratedComponent19Widget.dart';
import 'package:flutterapp/sabsusapp/generatedfototporolwidget/generated/GeneratedWidget278.dart';
import 'package:flutterapp/sabsusapp/generatedfototporolwidget/generated/GeneratedWidget277.dart';
import 'package:flutterapp/sabsusapp/generatedfototporolwidget/generated/GeneratedWidget279.dart';
import 'package:flutterapp/sabsusapp/generatedfototporolwidget/generated/GeneratedButtonsWidget125.dart';

/* Frame fotot porol
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFototporolWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 249, 247, 252),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 45.0,
                child: GeneratedWidget277(),
              ),
              Positioned(
                left: 22.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 56.0,
                child: GeneratedWidget278(),
              ),
              Positioned(
                left: 22.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 100.0,
                child: GeneratedComponent18Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 100.0,
                child: GeneratedComponent19Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 44.0,
                child: GeneratedWidget279(),
              ),
              Positioned(
                left: 22.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 52.0,
                child: GeneratedButtonsWidget125(),
              )
            ]),
      ),
    ));
  }
}
