import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget387.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedButtonsWidget520.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget384.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedWidget964.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedWidget963.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget389.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedGroup3356Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget385.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedADDnoWidget66.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget390.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedFrame3249Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget388.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget391.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedMenuVerticalWidget146.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget386.dart';
import 'package:flutterapp/sabsusapp/generatedaddclientwidget/generated/GeneratedInputTextWidget392.dart';

/* Frame add client
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddclientWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1666.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1666.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 40.0,
                            right: null,
                            bottom: null,
                            width: 348.0,
                            height: 22.0,
                            child: GeneratedWidget963(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 80.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 148.0,
                            child: GeneratedFrame3249Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 248.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget384(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 331.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget385(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 414.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 65.0,
                            child: GeneratedInputTextWidget386(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 499.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 36.0,
                            child: GeneratedMenuVerticalWidget146(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 555.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 65.0,
                            child: GeneratedInputTextWidget387(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 640.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget388(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 723.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget389(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 806.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget390(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 889.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget391(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 972.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget392(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1055.0,
                            right: null,
                            bottom: null,
                            width: 351.0,
                            height: 21.0,
                            child: GeneratedWidget964(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1091.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 430.0,
                            child: GeneratedGroup3356Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1541.0,
                            right: null,
                            bottom: null,
                            width: 232.51199340820312,
                            height: 40.0,
                            child: GeneratedButtonsWidget520(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1601.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 40.0,
                            child: GeneratedADDnoWidget66(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
