import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedmessegeprodovecwidget/generated/GeneratedFrame3458Widget54.dart';
import 'package:flutterapp/sabsusapp/generatedmessegeprodovecwidget/generated/GeneratedFluorWidget12.dart';
import 'package:flutterapp/sabsusapp/generatedmessegeprodovecwidget/generated/GeneratedFrame701Widget8.dart';

/* Frame messegeprodovec
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessegeprodovecWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 93.0,
          child: GeneratedFrame3458Widget54(),
        ),
        Positioned(
          left: 0.0,
          top: 138.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 586.0,
          child: GeneratedFrame701Widget8(),
        ),
        Positioned(
          left: 0.0,
          top: 744.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 100.0,
          child: GeneratedFluorWidget12(),
        )
      ]),
    ));
  }
}
