import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedNamestolbWidget.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedAppbarWidget84.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedNameWidget31.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedKolichestvoWidget.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedProsessWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedIngridientinfoWidget.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedButtonsssWidget.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedPhotoWidget5.dart';
import 'package:flutterapp/sabsusapp/generatedtexcardmoredishwidget/generated/GeneratedPoloskaWidget.dart';

/* Frame tex. card more dish
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTexcardmoredishWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 30.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedAppbarWidget84(),
        ),
        Positioned(
          left: 118.85917663574219,
          top: 112.0,
          right: null,
          bottom: null,
          width: 152.28164672851562,
          height: 147.0,
          child: GeneratedPhotoWidget5(),
        ),
        Positioned(
          left: 118.5,
          top: 279.0,
          right: null,
          bottom: null,
          width: 153.0,
          height: 20.0,
          child: GeneratedNameWidget31(),
        ),
        Positioned(
          left: 133.0,
          top: 319.0,
          right: null,
          bottom: null,
          width: 124.0,
          height: 20.0,
          child: GeneratedKolichestvoWidget(),
        ),
        Positioned(
          left: 22.0,
          top: 359.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 16.0,
          child: GeneratedNamestolbWidget(),
        ),
        Positioned(
          left: 22.0,
          top: 395.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 1.0,
          child: GeneratedPoloskaWidget(),
        ),
        Positioned(
          left: 22.0,
          top: 416.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 18.0,
          child: GeneratedIngridientinfoWidget(),
        ),
        Positioned(
          left: 22.0,
          top: 454.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 74.0,
          child: GeneratedProsessWidget1(),
        ),
        Positioned(
          left: 22.0,
          top: 548.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.0,
          child: GeneratedButtonsssWidget(),
        )
      ]),
    ));
  }
}
