import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedtabelwidget2/generated/GeneratedFrame720Widget11.dart';
import 'package:flutterapp/sabsusapp/generatedtabelwidget2/generated/GeneratedMenuVerticalWidget242.dart';
import 'package:flutterapp/sabsusapp/generatedtabelwidget2/generated/GeneratedGroup3445Widget5.dart';
import 'package:flutterapp/sabsusapp/generatedtabelwidget2/generated/GeneratedTabelWidget3.dart';

/* Frame tabel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTabelWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedFrame720Widget11(),
        ),
        Positioned(
          left: 22.0,
          top: 127.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 44.0,
          child: GeneratedMenuVerticalWidget242(),
        ),
        Positioned(
          left: 22.0,
          top: 211.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 191.0,
          child: GeneratedGroup3445Widget5(),
        ),
        Positioned(
          left: 22.5,
          top: 442.0,
          right: null,
          bottom: null,
          width: 345.0,
          height: 94.0,
          child: GeneratedTabelWidget3(),
        )
      ]),
    ));
  }
}
