import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedRectangle1832Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedMenuVerticalWidget13.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedFrame3458Widget4.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedInputTextWidget15.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedWidget48.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedInputTextWidget12.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedInputTextWidget11.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedInputTextWidget13.dart';
import 'package:flutterapp/sabsusapp/generatedadressredwidget/generated/GeneratedInputTextWidget14.dart';

/* Frame Adress red
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAdressredWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 778.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8923076923076924;

            final double height = constraints.maxHeight * 0.028277634961439587;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.05141388174807198,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedWidget48(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8871794871794871;

            final double height = constraints.maxHeight * 0.31362467866323906;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.09768637532133675,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedRectangle1832Widget1(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8871794871794871;

            final double height = constraints.maxHeight * 0.08354755784061697;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.4318766066838046,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedInputTextWidget11(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8871794871794871;

            final double height = constraints.maxHeight * 0.05398457583547558;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.5359897172236504,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedInputTextWidget12(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8871794871794871;

            final double height = constraints.maxHeight * 0.05398457583547558;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.6105398457583547,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedInputTextWidget13(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8871794871794871;

            final double height = constraints.maxHeight * 0.05398457583547558;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.6850899742930592,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedInputTextWidget14(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8871794871794871;

            final double height = constraints.maxHeight * 0.05398457583547558;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.7596401028277635,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedInputTextWidget15(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: null,
          right: 0.0,
          bottom: null,
          width: null,
          height: 36.0,
          child: TransformHelper.translate(
              x: 0.00,
              y: 278.00,
              z: 0,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        child: GeneratedMenuVerticalWidget13(),
                      ))
                ]);
              })),
        ),
        Positioned(
          left: 22.0,
          top: 701.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 52.0,
          child: GeneratedFrame3458Widget4(),
        )
      ]),
    ));
  }
}
