import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedredcategorynumenklatyrawidget/generated/GeneratedFrame3473Widget135.dart';
import 'package:flutterapp/sabsusapp/generatedredcategorynumenklatyrawidget/generated/GeneratedADDnoWidget27.dart';

/* Frame red  category numenklatyra
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedcategorynumenklatyraWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 368.0,
            child: GeneratedFrame3473Widget135(),
          ),
          Positioned(
            left: 22.0,
            top: 428.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedADDnoWidget27(),
          )
        ]),
      ),
    ));
  }
}
