import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedcallwidget/generated/GeneratedEllipse220Widget4.dart';
import 'package:flutterapp/sabsusapp/generatedcallwidget/generated/GeneratedFrame3469Widget10.dart';
import 'package:flutterapp/sabsusapp/generatedcallwidget/generated/GeneratedAppbarWidget6.dart';
import 'package:flutterapp/sabsusapp/generatedcallwidget/generated/Generated3200Widget.dart';
import 'package:flutterapp/sabsusapp/generatedcallwidget/generated/GeneratedWidget42.dart';

/* Frame call
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCallWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 211, 191, 249),
              ),
            ),
            Positioned(
              left: 22.0,
              top: 25.0,
              right: null,
              bottom: null,
              width: 346.0,
              height: 62.0,
              child: GeneratedAppbarWidget6(),
            ),
            Positioned(
              left: 113.0,
              top: 206.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 164.0,
              child: GeneratedEllipse220Widget4(),
            ),
            Positioned(
              left: 22.0,
              top: 489.0,
              right: null,
              bottom: null,
              width: 348.0,
              height: 26.0,
              child: GeneratedWidget42(),
            ),
            Positioned(
              left: 22.0,
              top: 632.0,
              right: null,
              bottom: null,
              width: 351.0,
              height: 25.0,
              child: Generated3200Widget(),
            ),
            Positioned(
              left: 22.0,
              top: 771.0,
              right: null,
              bottom: null,
              width: 346.0,
              height: 52.0,
              child: GeneratedFrame3469Widget10(),
            )
          ]),
    ));
  }
}
