import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedRectangle1837Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/Generated48Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedFrame3463Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedFrame3462Widget20.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedFrame720Widget6.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedFrame3463Widget2.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedFrame3462Widget19.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedRectangle1838Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedFrame3462Widget18.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedRatingWidget9.dart';
import 'package:flutterapp/sabsusapp/generatedaboutzavedeniyawidget/generated/GeneratedFrame3470Widget.dart';

/* Frame about zavedeniya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutzavedeniyaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1168.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1168.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 25.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 62.0,
                            child: GeneratedFrame720Widget6(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 107.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 168.0,
                            child: GeneratedRectangle1837Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 295.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 45.0,
                            child: Generated48Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 360.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 20.0,
                            child: GeneratedRatingWidget9(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 400.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 60.0,
                            child: GeneratedFrame3463Widget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 480.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 20.0,
                            child: GeneratedFrame3462Widget18(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 520.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 20.0,
                            child: GeneratedFrame3462Widget19(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 560.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 240.0,
                            child: GeneratedFrame3463Widget2(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 820.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 64.0,
                            child: GeneratedFrame3462Widget20(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 904.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 179.0,
                            child: GeneratedRectangle1838Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 1103.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 40.0,
                            child: GeneratedFrame3470Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
