import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedtableprodovwwidget/generated/GeneratedFrame720Widget10.dart';
import 'package:flutterapp/sabsusapp/generatedtableprodovwwidget/generated/GeneratedGroup3445Widget4.dart';
import 'package:flutterapp/sabsusapp/generatedtableprodovwwidget/generated/GeneratedTaibelWidget6.dart';
import 'package:flutterapp/sabsusapp/generatedtableprodovwwidget/generated/GeneratedMenuVerticalWidget241.dart';

/* Frame tABLE prodovw
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTABLEprodovwWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedFrame720Widget10(),
        ),
        Positioned(
          left: 22.0,
          top: 107.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 44.0,
          child: GeneratedMenuVerticalWidget241(),
        ),
        Positioned(
          left: 22.0,
          top: 171.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 191.0,
          child: GeneratedGroup3445Widget4(),
        ),
        Positioned(
          left: 22.0,
          top: 382.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 102.0,
          child: GeneratedTaibelWidget6(),
        )
      ]),
    ));
  }
}
