import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedframe3431widget/generated/GeneratedFrame3431Widget1.dart';

/* Component Frame 3431
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3431Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 71.0,
      height: 38.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 71.0,
              height: 38.0,
              child: GeneratedFrame3431Widget1(),
            )
          ]),
    ));
  }
}
