import 'package:flutter/material.dart';

/* UndefinedNode samosiviz
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSamosivizWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
