import 'package:flutter/material.dart';

/* UndefinedNode Frame 3472
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3472Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
