import 'package:flutter/material.dart';

/* UndefinedNode Delivery Details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeliveryDetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
