import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderfinishwidget/generated/GeneratedAppbarWidget14.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderfinishwidget/generated/GeneratedADDnoWidget3.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryoderfinishwidget/generated/GeneratedFrame3469Widget20.dart';

/* Frame Delivery oder finish
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeliveryoderfinishWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 249, 247, 252),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedAppbarWidget14(),
              ),
              Positioned(
                left: 22.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 662.0,
                child: GeneratedFrame3469Widget20(),
              ),
              Positioned(
                left: 22.5,
                top: 779.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 40.0,
                child: GeneratedADDnoWidget3(),
              )
            ]),
      ),
    ));
  }
}
