import 'package:flutter/material.dart';

/* UndefinedNode bag shoping 3d
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBagshoping3dWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
