import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Rectangle Outer Gray Shadow
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangleOuterGrayShadowWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 150.0,
      height: 50.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(127, 117, 127, 138),
            offset: Offset(5.0, 5.0),
            blurRadius: 10.0,
          ),
          BoxShadow(
            color: Color.fromARGB(127, 255, 255, 255),
            offset: Offset(-5.0, -5.0),
            blurRadius: 10.0,
          )
        ],
      ),
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 20C0 8.9543 8.95431 0 20 0L130 0C141.046 0 150 8.95431 150 20L150 30C150 41.0457 141.046 50 130 50L75 50L20 50C8.9543 50 0 41.0457 0 30L0 20Z')
          ..setLinearGradient(
            startX: 75.0,
            startY: -1.5308085657314598e-15,
            endX: 75.0,
            endY: 49.99999999999999,
            colors: [
              Color.fromARGB(255, 235, 237, 240),
              Color.fromARGB(255, 242, 244, 246)
            ],
            colorStops: [0.0, 1.0],
          ),
      ]),
    ));
  }
}
