import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedvibornumenklwidget/generated/GeneratedButtonsWidget737.dart';
import 'package:flutterapp/sabsusapp/generatedvibornumenklwidget/generated/GeneratedButtonsWidget738.dart';

/* Frame vibor numenkl
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVibornumenklWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 338.0,
        height: 114.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 22.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 294.0,
            height: 52.0,
            child: GeneratedButtonsWidget737(),
          ),
          Positioned(
            left: 22.0,
            top: 62.0,
            right: null,
            bottom: null,
            width: 294.0,
            height: 52.0,
            child: GeneratedButtonsWidget738(),
          )
        ]),
      ),
    ));
  }
}
