import 'package:flutter/material.dart';

/* UndefinedNode add product
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddproductWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
