import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedframe3390widget1/generated/GeneratedFrame3473Widget212.dart';
import 'package:flutterapp/sabsusapp/generatedframe3390widget1/generated/GeneratedButtonsWidget616.dart';

/* Frame Frame 3390
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3390Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 326.0,
      height: 210.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        Positioned(
          left: 3.0,
          top: 3.0,
          right: null,
          bottom: null,
          width: 320.0,
          height: 132.0,
          child: GeneratedFrame3473Widget212(),
        ),
        Positioned(
          left: 89.5,
          top: 155.0,
          right: null,
          bottom: null,
          width: 147.0,
          height: 52.0,
          child: GeneratedButtonsWidget616(),
        )
      ]),
    ));
  }
}
