import 'package:flutter/material.dart';

/* UndefinedNode sell vertikall
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSellvertikallWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
