import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedchaeviedrivewidget/generated/GeneratedAppbarWidget4.dart';
import 'package:flutterapp/sabsusapp/generatedchaeviedrivewidget/generated/GeneratedFrame3469Widget6.dart';
import 'package:flutterapp/sabsusapp/generatedchaeviedrivewidget/generated/GeneratedFrame3469Widget1.dart';

/* Frame chaevie drive
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChaeviedriveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 249, 247, 252),
              ),
            ),
            Positioned(
              left: 22.0,
              top: 25.0,
              right: null,
              bottom: null,
              width: 346.0,
              height: 62.0,
              child: GeneratedAppbarWidget4(),
            ),
            Positioned(
              left: 28.0,
              top: 107.0,
              right: null,
              bottom: null,
              width: 334.0,
              height: 640.0,
              child: GeneratedFrame3469Widget1(),
            ),
            Positioned(
              left: 22.0,
              top: 767.0,
              right: null,
              bottom: null,
              width: 346.0,
              height: 52.0,
              child: GeneratedFrame3469Widget6(),
            )
          ]),
    ));
  }
}
