import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedWidget49.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedFrame3458Widget6.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedMenuVerticalWidget14.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedWidget51.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedButtonsWidget51.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedWidget54.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedFrame3458Widget5.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedFrame3457Widget8.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedComponent25Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sabsusapp/generatedinfoprofiladdwidget/generated/GeneratedComponent24Widget.dart';

/* Frame info profil add
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfoprofiladdWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 40.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 24.0,
          child: GeneratedWidget49(),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8923076923076924;

            final double height = constraints.maxHeight * 0.030805687203791468;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.0995260663507109,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedWidget51(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 110.0,
          top: 128.0,
          right: null,
          bottom: null,
          width: 170.0,
          height: 148.0,
          child: GeneratedFrame3457Widget8(),
        ),
        Positioned(
          left: 22.0,
          top: 296.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 58.0,
          child: GeneratedComponent24Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 374.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 60.0,
          child: GeneratedFrame3458Widget5(),
        ),
        Positioned(
          left: 22.0,
          top: 454.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 60.0,
          child: GeneratedComponent25Widget(),
        ),
        Positioned(
          left: 0.0,
          top: 0.0,
          right: 0.0,
          bottom: 0.0,
          width: null,
          height: null,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            final double width = constraints.maxWidth * 0.8923076923076924;

            final double height = constraints.maxHeight * 0.027251184834123223;

            return Stack(children: [
              TransformHelper.translate(
                  x: constraints.maxWidth * 0.05641025641025641,
                  y: constraints.maxHeight * 0.6327014218009479,
                  z: 0,
                  child: Container(
                    width: width,
                    height: height,
                    child: GeneratedWidget54(),
                  ))
            ]);
          }),
        ),
        Positioned(
          left: 0.0,
          top: null,
          right: 0.0,
          bottom: null,
          width: null,
          height: 40.0,
          child: TransformHelper.translate(
              x: 0.00,
              y: 173.00,
              z: 0,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        child: GeneratedButtonsWidget51(),
                      ))
                ]);
              })),
        ),
        Positioned(
          left: 0.0,
          top: null,
          right: 0.0,
          bottom: null,
          width: null,
          height: 36.0,
          child: TransformHelper.translate(
              x: 0.00,
              y: 231.00,
              z: 0,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8871794871794871;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05641025641025641,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        child: GeneratedMenuVerticalWidget14(),
                      ))
                ]);
              })),
        ),
        Positioned(
          left: 22.0,
          top: 691.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 52.0,
          child: GeneratedFrame3458Widget6(),
        )
      ]),
    ));
  }
}
