import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedwindowszavedeniewidget/generated/GeneratedNazvanieWidget.dart';
import 'package:flutterapp/sabsusapp/generatedwindowszavedeniewidget/generated/GeneratedMenuVerticalWidget243.dart';
import 'package:flutterapp/sabsusapp/generatedwindowszavedeniewidget/generated/GeneratedAppbarWidget83.dart';
import 'package:flutterapp/sabsusapp/generatedwindowszavedeniewidget/generated/GeneratedOdersWidget1.dart';

/* Frame windows zavedenie
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWindowszavedenieWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 22.0,
          top: 40.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 62.0,
          child: GeneratedAppbarWidget83(),
        ),
        Positioned(
          left: 22.0,
          top: 122.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 36.0,
          child: GeneratedMenuVerticalWidget243(),
        ),
        Positioned(
          left: 22.0,
          top: 178.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 44.0,
          child: GeneratedNazvanieWidget(),
        ),
        Positioned(
          left: 22.0,
          top: 242.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 76.0,
          child: GeneratedOdersWidget1(),
        )
      ]),
    ));
  }
}
