import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedframe3473widget339/generated/GeneratedFrame3488Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedframe3473widget339/generated/GeneratedPoickWidget45.dart';
import 'package:flutterapp/sabsusapp/generatedframe3473widget339/generated/GeneratedFrame3489Widget.dart';

/* Frame Frame 3473
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame3473Widget339 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 377.0,
      height: 578.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(127, 158, 158, 158),
            offset: Offset(5.0, 10.0),
            blurRadius: 25.0,
          ),
          BoxShadow(
            color: Color.fromARGB(255, 255, 255, 255),
            offset: Offset(-8.0, -8.0),
            blurRadius: 20.0,
          )
        ],
      ),
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.circular(20.0),
          child: Container(
            color: Color.fromARGB(255, 255, 255, 255),
          ),
        ),
        Positioned(
          left: 10.0,
          top: 20.0,
          right: null,
          bottom: null,
          width: 367.0,
          height: 38.0,
          child: GeneratedPoickWidget45(),
        ),
        Positioned(
          left: 10.0,
          top: 78.0,
          right: null,
          bottom: null,
          width: 367.0,
          height: 230.0,
          child: GeneratedFrame3488Widget1(),
        ),
        Positioned(
          left: 10.0,
          top: 328.0,
          right: null,
          bottom: null,
          width: 367.0,
          height: 230.0,
          child: GeneratedFrame3489Widget(),
        )
      ]),
    ));
  }
}
