import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedinfoworkerwidget/generated/GeneratedWidget25.dart';
import 'package:flutterapp/sabsusapp/generatedinfoworkerwidget/generated/GeneratedWidget26.dart';
import 'package:flutterapp/sabsusapp/generatedinfoworkerwidget/generated/GeneratedFrame3467Widget.dart';
import 'package:flutterapp/sabsusapp/generatedinfoworkerwidget/generated/GeneratedEllipse220Widget.dart';
import 'package:flutterapp/sabsusapp/generatedinfoworkerwidget/generated/GeneratedFrame3469Widget.dart';
import 'package:flutterapp/sabsusapp/generatedinfoworkerwidget/generated/GeneratedAppbarWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedinfoworkerwidget/generated/GeneratedGroup3467Widget.dart';
import 'package:flutterapp/sabsusapp/generatedinfoworkerwidget/generated/GeneratedGroup3468Widget.dart';

/* Frame info worker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfoworkerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 62.0,
          child: GeneratedAppbarWidget1(),
        ),
        Positioned(
          left: 113.0,
          top: 107.0,
          right: null,
          bottom: null,
          width: 164.0,
          height: 164.0,
          child: GeneratedEllipse220Widget(),
        ),
        Positioned(
          left: 0.0,
          top: 291.0,
          right: null,
          bottom: null,
          width: 395.0,
          height: 21.0,
          child: GeneratedWidget25(),
        ),
        Positioned(
          left: 0.0,
          top: 327.0,
          right: null,
          bottom: null,
          width: 392.0,
          height: 26.0,
          child: GeneratedWidget26(),
        ),
        Positioned(
          left: 0.0,
          top: 371.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 30.0,
          child: GeneratedFrame3469Widget(),
        ),
        Positioned(
          left: 55.0,
          top: 421.0,
          right: null,
          bottom: null,
          width: 280.0,
          height: 150.0,
          child: GeneratedGroup3467Widget(),
        ),
        Positioned(
          left: 55.0,
          top: 591.0,
          right: null,
          bottom: null,
          width: 280.0,
          height: 150.0,
          child: GeneratedGroup3468Widget(),
        ),
        Positioned(
          left: 0.0,
          top: 761.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 64.0,
          child: GeneratedFrame3467Widget(),
        )
      ]),
    ));
  }
}
