import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedpovarmessegwidget/generated/GeneratedFrame701Widget10.dart';
import 'package:flutterapp/sabsusapp/generatedpovarmessegwidget/generated/GeneratedFluorWidget20.dart';
import 'package:flutterapp/sabsusapp/generatedpovarmessegwidget/generated/GeneratedAppbarWidget87.dart';

/* Frame povar messeg
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPovarmessegWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 859.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 93.0,
            child: GeneratedAppbarWidget87(),
          ),
          Positioned(
            left: 0.0,
            top: 141.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 595.0,
            child: GeneratedFrame701Widget10(),
          ),
          Positioned(
            left: 0.0,
            top: 759.0,
            right: null,
            bottom: null,
            width: 390.0,
            height: 100.0,
            child: GeneratedFluorWidget20(),
          )
        ]),
      ),
    ));
  }
}
