import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedhomeuprwidget/generated/GeneratedFluorWidget14.dart';
import 'package:flutterapp/sabsusapp/generatedhomeuprwidget/generated/GeneratedFrame3469Widget26.dart';

/* Frame home upr
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeuprWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1502.80126953125,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1502.80126953125,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 40.0,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 1342.80126953125,
                            child: GeneratedFrame3469Widget26(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 1402.80126953125,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 100.0,
                            child: GeneratedFluorWidget14(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
