import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedsellclientwidget/generated/GeneratedFrame3388Widget.dart';
import 'package:flutterapp/sabsusapp/generatedsellclientwidget/generated/GeneratedComponent9Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedsellclientwidget/generated/GeneratedFrame3458Widget49.dart';

/* Frame sellclient
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSellclientWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 0.0,
          top: 25.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 93.0,
          child: GeneratedFrame3458Widget49(),
        ),
        Positioned(
          left: 1.3917593955993652,
          top: 136.87353515625,
          right: null,
          bottom: null,
          width: 390.0,
          height: 479.0,
          child: GeneratedFrame3388Widget(),
        ),
        Positioned(
          left: 0.0,
          top: 637.0,
          right: null,
          bottom: null,
          width: 390.0,
          height: 207.0,
          child: GeneratedComponent9Widget1(),
        )
      ]),
    ));
  }
}
