import 'package:flutter/material.dart';

/* UndefinedNode Messeg
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessegWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
