import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedFrame3336Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedFrame3337Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedFrame3336Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedADDnoWidget16.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedWidget643.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedFrame3339Widget.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedWidget644.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedInputTextWidget87.dart';
import 'package:flutterapp/sabsusapp/generatedaddingridientwidget/generated/GeneratedInputTextWidget84.dart';

/* Frame add ingridient
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddingridientWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1058.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1058.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 40.0,
                            right: null,
                            bottom: null,
                            width: 348.0,
                            height: 22.0,
                            child: GeneratedWidget643(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 80.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedInputTextWidget84(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 163.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedFrame3336Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 246.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 63.0,
                            child: GeneratedFrame3339Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 329.0,
                            right: null,
                            bottom: null,
                            width: 351.0,
                            height: 21.0,
                            child: GeneratedWidget644(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 365.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 147.0,
                            child: GeneratedFrame3336Widget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 532.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 65.0,
                            child: GeneratedInputTextWidget87(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 617.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 356.0,
                            child: GeneratedFrame3337Widget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 993.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 40.0,
                            child: GeneratedADDnoWidget16(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
