import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedButtonsWidget13.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedButtonsWidget12.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedFrame3462Widget2.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedFrame3462Widget1.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedOrdercompletedWidget.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedOrdercompletedWidget2.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedLineWidget.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedFrame3463Widget.dart';
import 'package:flutterapp/sabsusapp/generatedoderprinyatwidget/generated/GeneratedFoodieAPPLogo3Trns1Widget.dart';

/* Frame oder prinyat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOderprinyatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 390.0,
      height: 844.0,
      child:
          Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
        ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 249, 247, 252),
          ),
        ),
        Positioned(
          left: 117.61719512939453,
          top: 25.0,
          right: null,
          bottom: null,
          width: 154.76560974121094,
          height: 139.0,
          child: GeneratedFoodieAPPLogo3Trns1Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 184.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 31.0,
          child: GeneratedOrdercompletedWidget(),
        ),
        Positioned(
          left: 22.0,
          top: 235.0,
          right: null,
          bottom: null,
          width: 348.0,
          height: 31.0,
          child: GeneratedOrdercompletedWidget2(),
        ),
        Positioned(
          left: 22.0,
          top: 284.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 16.0,
          child: GeneratedFrame3462Widget1(),
        ),
        Positioned(
          left: 22.0,
          top: 320.0,
          right: null,
          bottom: null,
          width: 346.0,
          height: 40.6781005859375,
          child: GeneratedFrame3462Widget2(),
        ),
        Positioned(
          left: 22.0,
          top: 380.6781005859375,
          right: null,
          bottom: null,
          width: 346.0,
          height: 78.39378356933594,
          child: GeneratedFrame3463Widget(),
        ),
        Positioned(
          left: 22.0,
          top: 479.0718994140625,
          right: null,
          bottom: null,
          width: 346.0,
          height: 1.0,
          child: GeneratedLineWidget(),
        ),
        Positioned(
          left: 132.0,
          top: 500.0718994140625,
          right: null,
          bottom: null,
          width: 126.0,
          height: 40.0,
          child: GeneratedButtonsWidget12(),
        ),
        Positioned(
          left: 114.5,
          top: 560.0718994140625,
          right: null,
          bottom: null,
          width: 161.0,
          height: 40.0,
          child: GeneratedButtonsWidget13(),
        )
      ]),
    ));
  }
}
