import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedNalichnieWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedKoplateWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedUclientaWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedAppbarWidget9.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedCommentWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedSdachaWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedMapWidget2.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedMoreadressWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedFrame3424Widget6.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedTerminalWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedPrinyatWidget1.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedInfoWidget.dart';
import 'package:flutterapp/sabsusapp/generateddeliveryodergivewidget/generated/GeneratedFrame3433Widget1.dart';

/* Frame Delivery oder give
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeliveryodergiveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 927.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 927.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 77.0,
                            child: GeneratedAppbarWidget9(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 97.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 50.0,
                            child: GeneratedInfoWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 167.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 176.0,
                            child: GeneratedMapWidget2(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 363.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 52.0,
                            child: GeneratedFrame3424Widget6(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 435.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedMoreadressWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 480.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 53.0,
                            child: GeneratedFrame3433Widget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 553.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedKoplateWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 598.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedNalichnieWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 643.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedUclientaWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 688.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedTerminalWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 733.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 25.0,
                            child: GeneratedSdachaWidget(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 778.0,
                            right: null,
                            bottom: null,
                            width: 346.0,
                            height: 64.0,
                            child: GeneratedCommentWidget(),
                          ),
                          Positioned(
                            left: 22.5,
                            top: 862.0,
                            right: null,
                            bottom: null,
                            width: 345.0,
                            height: 40.0,
                            child: GeneratedPrinyatWidget1(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
