import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedKoplateWidget3.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedMasscallWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedMapWidget4.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedCamentWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedOclienteWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedNalichnieWidget3.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedAppbarWidget11.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedStatusodersWidget1.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedFrame3424Widget9.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedFrame3431Widget26.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedFrame3432Widget10.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedFrame3424Widget10.dart';
import 'package:flutterapp/sabsusapp/generatedoderoldfinishwidget/generated/GeneratedFrame3425Widget6.dart';

/* Frame oder old finish
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOderoldfinishWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 988.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 381.0,
                    height: 988.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 77.0,
                            child: GeneratedAppbarWidget11(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 97.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 25.0,
                            child: GeneratedStatusodersWidget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 142.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 75.0,
                            child: GeneratedFrame3424Widget9(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 237.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 176.0,
                            child: GeneratedMapWidget4(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 433.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 72.0,
                            child: GeneratedFrame3424Widget10(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 525.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 25.0,
                            child: GeneratedFrame3425Widget6(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 570.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 53.0,
                            child: GeneratedOclienteWidget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 643.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 40.0,
                            child: GeneratedMasscallWidget1(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 703.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 25.0,
                            child: GeneratedKoplateWidget3(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 748.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 25.0,
                            child: GeneratedNalichnieWidget3(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 793.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 25.0,
                            child: GeneratedFrame3431Widget26(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 838.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 25.0,
                            child: GeneratedFrame3432Widget10(),
                          ),
                          Positioned(
                            left: 22.0,
                            top: 883.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 80.0,
                            child: GeneratedCamentWidget1(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
