import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedporoladminwidget/generated/GeneratedInputTextWidget79.dart';

/* Frame porol admin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPoroladminWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 843.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(76, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 70.0,
            top: 389.0,
            right: null,
            bottom: null,
            width: 250.0,
            height: 65.0,
            child: GeneratedInputTextWidget79(),
          )
        ]),
      ),
    ));
  }
}
