import 'package:flutter/material.dart';

/* UndefinedNode Buttons AES RED GREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonsAESREDGREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
