import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatedschetacompaniiwidget/generated/GeneratedAppbarWidget37.dart';
import 'package:flutterapp/sabsusapp/generatedschetacompaniiwidget/generated/GeneratedPoickWidget20.dart';
import 'package:flutterapp/sabsusapp/generatedschetacompaniiwidget/generated/GeneratedNamekolichesdvoaddWidget20.dart';
import 'package:flutterapp/sabsusapp/generatedschetacompaniiwidget/generated/GeneratedFrame3473Widget59.dart';
import 'package:flutterapp/sabsusapp/generatedschetacompaniiwidget/generated/GeneratedFrame3473Widget61.dart';

/* Frame scheta companii
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSchetacompaniiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 249, 247, 252),
            ),
          ),
          Positioned(
            left: 22.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 62.0,
            child: GeneratedAppbarWidget37(),
          ),
          Positioned(
            left: 22.0,
            top: 107.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 40.0,
            child: GeneratedNamekolichesdvoaddWidget20(),
          ),
          Positioned(
            left: 22.0,
            top: 167.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 38.0,
            child: GeneratedPoickWidget20(),
          ),
          Positioned(
            left: 22.0,
            top: 225.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 554.0,
            child: GeneratedFrame3473Widget59(),
          ),
          Positioned(
            left: 22.0,
            top: 799.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 20.0,
            child: GeneratedFrame3473Widget61(),
          )
        ]),
      ),
    ));
  }
}
