import 'package:flutter/material.dart';
import 'package:flutterapp/sabsusapp/generatednewsellwidget/generated/GeneratedFrame3458Widget48.dart';
import 'package:flutterapp/sabsusapp/generatednewsellwidget/generated/GeneratedFrame3473Widget210.dart';
import 'package:flutterapp/sabsusapp/generatednewsellwidget/generated/GeneratedFrame3482Widget.dart';

/* Frame newsell
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewsellWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1196.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 390.0,
                    height: 1196.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 249, 247, 252),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 25.0,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 93.0,
                            child: GeneratedFrame3458Widget48(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 138.0,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 684.0,
                            child: GeneratedFrame3473Widget210(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 842.0,
                            right: null,
                            bottom: null,
                            width: 390.0,
                            height: 354.0,
                            child: GeneratedFrame3482Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
